### ISSUE TITLE
Problème "échec de lecture" ou "fichiers introuvables" depuis Vstream Beta

### ISSUE THREAD

**Issue by Louis-Petit** [Up2Paste/Windows#10]
Depuis que j'ai mis là dernière beta de Vstream, j'arrive à me connecter aux différentes sources (notamment paste), les recherches s'effectuent sans soucis, par contre, il m'est impossible de lire le fichier sélectionné, j'ai soit "échec de lecture" soit "fichier introuvable" et même sur des fichiers paste qui fonctionnent.

**Comment by benking110181** [comment]
tu la prend là la beta
 ht          tps       ://minhaskamal.github.io          /DownGit/#/home?url=https:%2F%2Fgithub.com%2FKodi-vStream%2Fvenom-xbmc-addons%2Ftree%2FBeta%2F      plugin.video.vstream 

ou sur le github download branch beta

**Comment by noway80** [comment]
J avais le même problème que toi
Bon j ai trouvé, pour lecture dans mon compte upto , après mise à jour , l option était "toujours me demander" et j ai remis sur "upto direct"
Tout ok !!

**Comment by Louis-Petit** [comment]
L'option dans l'interface vstream ou sur ton compte uptobox?

**Comment by benking110181** [comment]
paramétre vstream premium/login mode par defaut

**Comment by Louis-Petit** [comment]
Alors... je l'ai fait.
Je suis allé sur source -> paste -> films de Benking 
Dans un premier temps ca le mets "échec de lecture"
Ensuite je reste appuyé sur le même film afin d'afficher le menu, puis lire..
Et là il me mets "uptobox identification reussie" et "fichier introuvable"

**Comment by benking110181** [comment]
tu est parti d'une fresh install

**Comment by benking110181** [comment]
et sur les autres sources ca fonctionne

**Comment by alKODIque** [comment]
@Louis-Petit 
c'est bien un compte premium et non gratuit? (me souviens plus)
Car les comptes gratuits ont une limite de 2h de visionnage par jour

**Comment by alKODIque** [comment]
Comme noway a mentionné, c'est bien l'option ''Rester en direct via uptobox'' qu'il faut sélectionner:

![uptobox](https://user-images.githubusercontent.com/49578130/94958414-7bf64800-04bd-11eb-91c8-76ab9d496a41.png)

**Comment by noway80** [comment]
Oui voila , on voit les pros 
@Louis-Petit 
T inkietes pas , personne ne me comprend 😉

**Comment by Louis-Petit** [comment]
Je t'avais très bien compris et effectivement j'étais comme toi "me demander avant" et je l'ai changé en uptobox direct..
Mais ca m'a fait ce que j'ai écris plus haut.

**Comment by Louis-Petit** [comment]
> tu est parti d'une fresh install

Non toujours pas... je suis rentré chez moi et j ai vu le reply de noway... donc j'ai essayé avant de faire un clean 😊

**Comment by Louis-Petit** [comment]
> @Louis-Petit
> c'est bien un compte premium et non gratuit? (me souviens plus)
> Car les comptes gratuits ont une limite de 2h de visionnage par jour

Yes ma'ame premium jusqu'en 2022...


Ps: i hate you 😛

**Comment by alKODIque** [comment]
> > @Louis-Petit
> > c'est bien un compte premium et non gratuit? (me souviens plus)
> > Car les comptes gratuits ont une limite de 2h de visionnage par jour
> 
> Yes ma'ame premium jusqu'en 2022...
> 
> Ps: i hate you 😛

I hate you MORE lol

**Comment by benking110181** [comment]
Change le nom du dossier comme expliquer cette apres midi et installe juste repo vstream et ensuite test et ensuite la bêta mais copie le dossier du zip comme je t'avais expliquer car il y a un bug par fonction installer par zip dans kodi

**Comment by noway80** [comment]
Yes ma'ame premium jusqu'en 2022...

Ps: i hate you
Oh la la , un gang québécois 🤪

**Comment by benking110181** [comment]
@noway80 toi ca fonctionne tu a réussi le transfert zip sur shield

**Comment by Louis-Petit** [comment]
> Change le nom du dossier comme expliquer cette apres midi et installe juste repo vstream et ensuite test et ensuite la bêta mais copie le dossier du zip comme je t'avais expliquer car il y a un bug par fonction installer par zip dans kodi

J'avoue avoir eu une journée chargée et pas la motiv' de le faire là de suite..
Demain matin je fais un clean...
J'installe kodi, je mets la version non bêta de vstream..
Je test, je me lance dans artic horizon.
Une fois en place je fais comme tu m'as dit avec les @ et j'installe la bêta via le desktop... et de là je verrais ce qui cloche.... ou pas 🤣🤣🤣🤣

**Comment by Louis-Petit** [comment]
> Yes ma'ame premium jusqu'en 2022...
> 
> Ps: i hate you
> Oh la la , un gang québécois 🤪

Try me 🤣🤣🤣🤣

**Comment by Louis-Petit** [comment]
> Yes ma'ame premium jusqu'en 2022...
> 
> Ps: i hate you
> Oh la la , un gang québécois 🤪

🤣🤣🤣🤣 ah non non... je suis du var

**Comment by benking110181** [comment]
En fait si tu fait arrobase et que tu lance kodi ca te fait comme fresh install ensuite tu installe repo vstream

**Comment by alKODIque** [comment]
> > Yes ma'ame premium jusqu'en 2022...
> > Ps: i hate you
> > Oh la la , un gang québécois 🤪
> 
> 🤣🤣🤣🤣 ah non non... je suis du var

Bah quoi?
Comme si c'était une maladie d'être Québécoise 😂😂😂

**Comment by Louis-Petit** [comment]
> En fait si tu fait arrobase et que tu lance kodi ca te fait comme fresh install ensuite tu installe repo vstream

Oui je comprends ce que tu dis... en effet je n'y avais pas pensé 😊
On reconnaît un pro d'un Newb 😊😊

**Comment by Louis-Petit** [comment]
> > > Yes ma'ame premium jusqu'en 2022...
> > > Ps: i hate you
> > > Oh la la , un gang québécois 🤪
> > 
> > 
> > 🤣🤣🤣🤣 ah non non... je suis du var
> 
> Bah quoi?
> Comme si c'était une maladie d'être Québécoise 😂😂😂

Loin de moi cette pensée 😊

**Comment by noway80** [comment]
Moi qui suis belge , ca fait une drôle d equipe🤣🤣

**Comment by alKODIque** [comment]
> Moi qui suis belge , ca fait une drôle d equipe🤣🤣

Nous sommes "Les Impondérables" 😆🙌

**Comment by Louis-Petit** [comment]
Je ne trouve pas la branche download sur le git... c'est moi ou elle est cachée ? 😅

**Comment by Louis-Petit** [comment]
Bon et bien après un clean et un fresh install tout fonctionne de nouveau.
Je dois fermer cette issue ou je la laisse au cas ou qqn se retrouve dans ce cas de figure?

**Comment by sizanic** [comment]
> Je dois fermer cette issue ou je la laisse au cas ou qqn se retrouve dans ce cas de figure?

@Louis-Petit 
tu peux fermer cette issue 👍
