### ISSUE TITLE
Liste Acteurs

### ISSUE THREAD

**Issue by PassionFlix** [Up2Paste/Windows#11]
Salut tout le monde, je voudrais partager avec vous ma liste d'acteurs pour vous faciliter la tache lors de la création de votre config U2P
La liste étant trop longue désormais avec 226 Acteurs ajoutés, j'ai créé un paste 
Cast : **Cxiqm3tV**

_(ATTENTION ! Ceci n'est pas un paste à mettre dans votre VSTREAM mais bien dans le fichier conf de votre U2P section [Cast] )_

**Comment by PassionFlix** [comment]
@noway80 Ca donne quoi si je mets dans ma liste d'acteurs ? 
https://www.themoviedb.org/person/33663-donald-trump?language=fr

**Comment by noway80** [comment]
Des navets 😁😁

**Comment by PassionFlix** [comment]
Ca va faire planter U2P non ?

**Comment by alKODIque** [comment]
@PassionFlix 

J'ai ajouté ma mini liste d'acteurs à la méga-tienne 🤓

Tu as fait tout un travail wahou!!!!  

De mon côté, à temps perdu, j'essaie de faire les traductions et ajouts d'information pour les acteurs qui n'en ont pas... 

J'ai d'ailleurs teminé la liste des Réalisateurs il y a quelques jours. 

Je sais, je sais...
J'avais déjà dit que je voulais seulement en proposer quelques-uns à découvrir à l'intérieur de ma collection mais n'oublions pas un fait: 

**_Je suis une fille, alors il est normal que je change d'idée, c'est dans mes gènes; et personne ne devrait donc en être étonné hein 😜😝_** 

Voilà le résultat de nos 2 listes combinées, si tu as envie de mettre à jour ton paste ;)

Bon week-end!

[ACTEURS.txt](https://github.com/Up2Paste/Windows/files/5357321/ACTEURS.txt)

**Comment by PassionFlix** [comment]
Super @alKODIque , ton boulot pour les réalisateurs a été enormissime 
Moi aussi je voulais genre 20 acteurs principaux et puis de fils en aiguille...
Presque 180 mdr

Je fini un boulot sur des Animes qui me gave et je mets mon paste à jour volontiers 

Bon week-end a toi aussi

**Comment by PassionFlix** [comment]
@alKODIque paste CAST mis à jour et encore de nouveaux acteurs 
**Total des Acteurs sur la liste : 208**

**Comment by alKODIque** [comment]
@PassionFlix 
rassure-moi et confirme que mon bouc émissaire préféré mentionné plus haut ☝️ ne figure pas dans la liste 😂😂

**Comment by PassionFlix** [comment]
> @PassionFlix 
> rassure-moi et confirme que mon bouc émissaire préféré mentionné plus haut ☝️ ne figure pas dans la liste 😂😂

Tu parle du lien que j'avais mis à noway ? 😂

**Comment by PassionFlix** [comment]
@alKODIque merci beaucoup par contre d'avoir trié la liste 😉

**Comment by noway80** [comment]
Lol vous êtes cinglés,  vous vous rappelez qu on devez limiter a 10 acteurs 🤪😜

**Comment by alKODIque** [comment]
> @alKODIque merci beaucoup par contre d'avoir trié la liste 😉

C'était dans le but de cibler rapidement les doublons lorsque j'ai ajouté les tiens aux miens ;)

**Comment by PassionFlix** [comment]
10 acteurs par ligne noway parce que le fichier co fig se rempli

**Comment by PassionFlix** [comment]
> C'était dans le but de cibler rapidement les doublons lorsque j'ai ajouté les tiens aux miens ;)

C'est le top

**Comment by noway80** [comment]
New version 
Les acteurs sont sortis de config et sont dans un fichier txt au meme format que le vôtre, comme ca vous pourrez echanger

**Comment by alKODIque** [comment]
@noway80 
loll!! tu m'as fait rire fort et je suis toute seule !!!  Je vais m'interroger sur ma santé mentale maintenant :P

**Comment by PassionFlix** [comment]
En ligne séparé par ; c'est pas possible car ça bouffe 208 ligne pour le moment car c'est pas fini 😂

**Comment by noway80** [comment]
Non sérieux, la liste acteurs est extérieur 
Vous êtes des furieux des acteurs 😁

**Comment by alKODIque** [comment]
C'est la faute à @PassionFlix 
Moi, je ne suis qu'un mouton lol

**Comment by noway80** [comment]
Les 2 font la paire!!!😁

**Comment by PassionFlix** [comment]
Une équipe qui gagne 😉

**Comment by PassionFlix** [comment]
J'ai répondu à une demande de quelques utilisateurs

**Comment by alKODIque** [comment]
@PassionFlix 
J'ai inclu 4 acteurs québécois qui sont populaires ici... puisque tu as aussi des films québécois dans ta liste, je les ai ajouté. Tu ajoute si tu veux à la liste générale, c'est comme tu souhaites ;)

[ACTEURS.txt](https://github.com/Up2Paste/Windows/files/5359887/ACTEURS.txt)

**Comment by PassionFlix** [comment]
Heuuu ce sont lesquels ? Mdr

**Comment by alKODIque** [comment]
> Heuuu ce sont lesquels ? Mdr

38526 = Rémy Girard
90681 = Antoine Bertrand
32885 = Michel Côté
95956 = Luc Picard

**Comment by PassionFlix** [comment]
> 38526 = Rémy Girard
> 90681 = Antoine Bertrand
> 32885 = Michel Côté
> 95956 = Luc Picard

Je les rajoute de suite

**Comment by PassionFlix** [comment]
Mise a jour faite ;)

**Comment by PassionFlix** [comment]
Nouvelle mise à jour du paste Acteurs (217)

**Comment by alKODIque** [comment]
@PassionFlix 
Jai fait ajout d'un acteur: Vincent Lindon

[ACTEURS.txt](https://github.com/Up2Paste/Windows/files/5395358/ACTEURS.txt)

**Comment by PassionFlix** [comment]
@alKODIque je mets à jour dans un instant

**Comment by alKODIque** [comment]
@PassionFlix 
Tu vas faire une mise à jour de ton paste pour rien, je t'ai pas passé le fichier texte mis à jour 😂😂. Désolée, etreur de ma part

c'est 5443 = Vincent Lindon

**Comment by PassionFlix** [comment]
Mise à jour faite @alKODIque

**Comment by PassionFlix** [comment]
Mise a jour du paste Acteurs

Derniers Ajouts:

- Salma Hayek
- Antonio Banderas
- Jennifer Lopez
- Catherine Zeta-Jones
- Dolph Lundgren
- Andy Garcia
- John Cusak
