### ISSUE TITLE
problemes Anime

### ISSUE THREAD

**Issue by noway80** [Up2Paste/Windows#12]
@benking

voila la synthese, analyse log anime 

One Piece Kai 18 -   Arc Enies Lobby - part 6 - Pont de l'HÃ©sitation.mp4 | E01006
-- | --
One Piece Kai 18 - Arc Enies Lobby - part   5 - Buster Call.mp4 | E01005
One Piece Kai 18 - Arc Enies Lobby - part   4 - Tour Judiciaire.mp4 | E01004
One Piece Kai 18 - Arc Enies Lobby - part   3 - Les DÃ©mons d'Ohara.mp4 | E01003
One Piece Kai 18 - Arc Enies Lobby - part   2 - Tribunal.mp4 | E01002
One Piece Kai 18 - Arc Enies Lobby - part   1 - Assaut.mp4 | E01001
One Piece Kai 17 - Arc Rocketman.mp4 | E01017
One Piece Kai 16 - Arc Water Seven - part   3 - Tom.mp4 | E01003
One Piece Kai 16 - Arc Water Seven - part   2 - Complot.mp4 | E01002
One Piece Kai 16 - Arc Water Seven - part   1 - L'avenir de Merry.mp4 | E01001
One Piece Kai 15 - Arc Aokiji.mp4 | E01015
One Piece Kai 14 - Arc Davy Back   Fight.mp4 | E01014
One Piece Kai 29 - Nouvelle Ã¨re - part 2   - PrÃ©parations et Rendez-vous.mp4 | E01002
One Piece Kai 29 - Nouvelle Ã¨re - part 1   - Message.mp4 | E01001
One Piece Kai 28 - Arc PassÃ© de Luffy -   part 2 - DÃ©parts.mp4 | E01002
One Piece Kai 28 - Arc PassÃ© de Luffy -   part 1 - FrÃ¨res.mp4 | E01001
One Piece Kai 27 - Arc Marineford - part   4 - Fuir ou mourir.mp4 | E01004
One Piece Kai 27 - Arc Marineford - part   3 - LibÃ©ration.mp4 | E01003
One Piece Kai 27 - Arc Marineford - part   2 - Luffy et Barbe Blanche.mp4 | E01002
One Piece Kai 27 - Arc Marineford - part   1 -  Guerre totale.mp4 | E01001
One Piece Kai 26 - Arc Impel Down - part   4 - Evasion sans prÃ©cÃ©dent.mp4 | E01004
One Piece Kai 26 - Arc Impel Down - part   3 - 2e chance.mp4 | E01003
One Piece Kai 26 - Arc Impel Down - part   2 - Magellan.mp4 | E01002
One Piece Kai 26 - Arc Impel Down - part   1 - Infiltration.mp4 | E01001

le meme num en plusieurs parties , pas gerable 

a part ca, ne m'ai rien vu de particulier apres avoir reglé le SR-71 et x.264
j'ajout encore un filtre pour la contruction du paste

dis moi , tes anomalies en postant le resultAnim.csv

**Comment by benking110181** [comment]
Ne prend pas one pièce kai pour exemple il est pas sur tmdb. Et faut que je verifie si c que les kai , yabai qui on des part .
Ta vu jai un problème d'accent aussi.
Le sr-71 c est l'uploader ou traducteur studio ou fan
X264 etc c'est un problème avec les crochets j'ai la même erreur dans les films avec 1080p ou vf en crochet
Ensuite j'ai pas regarder pour trouver le nom occidental car si sur tmdb le nom de animé écrit en asiatique...
Je rajouterai quelque un et scan quand j'aurai trier ce qui ne va pas.

**Comment by noway80** [comment]
Ok et me donner le resultAnime
Si tu veux , tu m envoies ton mediaStrea....bd
J effacerai la partie anime pour refaire une recherche propre

**Comment by benking110181** [comment]
[anime.zip](https://github.com/Up2Paste/Windows/files/5324055/anime.zip)

**Comment by benking110181** [comment]
mediavstream c celui que tu ma donner si je me trompe pas que j'avais coller avant le scan

**Comment by noway80** [comment]
Oui

**Comment by Up2Paste** [comment]
Bonjour.
Ce sujet est-il toujours en cours ?
