### ISSUE TITLE
Filtres de censure

### ISSUE THREAD

**Issue by alKODIque** [Up2Paste/Windows#13]
C'est a n'y rien comprendre..

J'ai créé une liste de "Films suscitant la controverse" et je m'aperçois à l'instant que ce film a passé le filtre de censure!!! Je n'ai visionné que quelques minutes du début pour voir qu'il ne devrait pas être là:

https://www.themoviedb.org/movie/84520-the-bunny-game

Et pas de panique! je retire!

**Comment by PassionFlix** [comment]
La photo porte à confusion ou ce sont mes yeux qui me joue un tour?

**Comment by alKODIque** [comment]
@noway80 
Même en ayant retiré de mon dossier racine les films censurés et les avoir ajouté a mon dossier "Adultes" non répertorié pour le scan, ils demeurent toujours dans mon fichier censure.

J'ai également  dû complètement retirer le film "The bunny Story" de mon compte uptobox afin qu'il ne soit plus présent dans ma liste "Films suscitant la controverse".   En le déplaçant seulement dans mon dossier "Adultes" de mon compte uptobox, il demeurait présentement dans mon fichier extract donc toujours disponible au visionnage pour les utilisateurs de mon paste.

**Comment by noway80** [comment]
Si le dossier adulte est dans films , il sera accepté et ce n est pas parce qu il est dans ce dossier qu il ne sera pas censuré

**Comment by noway80** [comment]
J ai testé le déplacement d un fichier en dehors du dossier Racine,  il disparaît du paste

**Comment by alKODIque** [comment]
@noway80 
Ouais...
je me sentais un peu stupide héhé

Delà le long délai pour mon retour... Fallait que je piétine mon Égo 🤪😝

**Comment by noway80** [comment]
😉

**Comment by PassionFlix** [comment]
Le film RAMPART de 2011 est reconnu en censure 18 sur TMDB et tous public sur IMDB
REPO MEN de 2010 aussi 18 sur TMDB et 12 sur IMDB

U2P prend les infos sur IMDB c'est bien ca ?
