### ISSUE TITLE
Le site Pastebin bloque l'accès

### ISSUE THREAD

**Issue by sizanic** [Up2Paste/Windows#14]
Il peut arriver que le site pastebin bloque l'accès à un paste.

Voilà ce que ça donne sur un navigateur :

![image](https://user-images.githubusercontent.com/47307622/95143839-775cb880-0777-11eb-9c2d-486815126cb2.png)

La source pastebin ne gère pas ce cas.

**Comment by PassionFlix** [comment]
Qu'elle est la solution dans ce cas?

**Comment by sizanic** [comment]
Une évolution de la source pasteBin est à prévoir pour gérer ce cas.

**Comment by sizanic** [comment]
Je crois que nous n'aurons pas ce problème car ce n'est pas cette adresse qui est utilisée, mais l'adresse vers les données brutes : 
`/pastebin/raw/`
