### ISSUE TITLE
[EVOLUTION] - Regrouper des liens pastes

### ISSUE THREAD

**Issue by sizanic** [Up2Paste/Windows#15]
Bon voilà, j'ai du revoir tous le code de la source Patebin :
https://github.com/Kodi-vStream/venom-xbmc-addons/commit/70ae76257d0b7b0e6cf9f382dc01f51bad3008ca

Mais la fonctionnalité de groupement des pastes est prête !
(Dispo dans la Bêta)

Donc on ne commence plus par saisir le lien paste mais d'abord un nom de "Dossier Pastebin".
A l'intérieur de ce dossier, il est possible d'ajouter plusieurs "Liens pastebin".

Il est possible de supprimer le dossier (et donc les liens vers les différents pastes).

Il n'est pas possible de supprimer un lien Paste dans un dossier.
Il faudra alors supprimer le dossier et remettre les pastes à conserver.

**Comment by PassionFlix** [comment]
ha ha tu m'interesse
Donc le principe, U2P va nous créer 2 paste au dela de 500ko et dans la beta de vstream on va rentrer un dossier puis dans ce dossier les 2 codes Pastebin correspondant à la source "PassionFlix" par exemple 
J'ai bien compris ? :)

**Comment by sizanic** [comment]
- On peut regrouper plusieurs paste de séries (ou de films) qui auraient été créés lors de la même génération U2P.

- On peut regrouper un paste de films et un paste de séries.
Par exemple pour un dossier Quebec 😉 

- On peut grouper plusieurs pastes de films venant de plusieurs contributeurs.


/!\ Il faut dans tous les cas que la ligne d'entête soit la même (même champs et même hebergeur)

=> Sinon, erreur lors de l'ajout du paste : "Format non supporté"

**Comment by PassionFlix** [comment]
Je vais tester immédiatement

**Comment by PassionFlix** [comment]
WOUAAAAAAAHHHHHHH
Je mis les 4 pastes de films présent dans l'issue [ICI](https://github.com/Kodi-vStream/venom-xbmc-addons/issues/3045) et c'est nickel, même les groupes "LISTE" des 4 pastes sont présents

**Comment by PassionFlix** [comment]
Par contre, pour un film il prend un lien au hazard ou il est censé nous proposer tous les liens ?

**Comment by sizanic** [comment]
Il n'y a pas de hasard 🤔 😆 

Autant les listes sont regroupées, les acteurs sont regroupés, les réalisateurs sont regroupés, les résolutions sont regroupées, les genres sont regroupés, les sagas sont regroupées, les séries sont regroupées.

**MAIS** les films en doublons ne sont pas regroupés.

Lorsque tu vois un film au début de ta liste _(Derniers ajouts)_, c'est un film disponible dans le premier paste que tu as renseigné : 
=> les liens proposés ne seront que ceux de ce paste.

Si ce même film existe dans un autre paste, il sera proposé de nouveau dans la liste mais beaucoup plus loin (avec les liens associés).

Cela se voit bien dans les sagas où les films sont rapprochés : 
![image](https://user-images.githubusercontent.com/47307622/95201063-aeff4b00-07df-11eb-9f3a-bcd0f83c1817.png)

La saga _Anaconda_ n'est proposée qu'une seule fois mais on voit que le premier film _Anaconda_ n'est proposé que dans un seul paste, les autres films sont proposés par deux pastes.


Pour les séries, elles sont bien regroupées, mais tu auras autant de fois de saisons qu'il y a de saisons en double dans les différents pastes : 
=> les épisodes ne sont pas regroupés dans une même saison.

![image](https://user-images.githubusercontent.com/47307622/95201660-84fa5880-07e0-11eb-8518-fe90c95d5838.png)

La série **_Stargate Universe_** n'apparait qu'une seule fois mais on voit que les deux saisons sont disponibles dans deux pastes.

**Comment by PassionFlix** [comment]
Ca devient un dossier paste multi liens
Si un lien n'est plus valide tu as des chances de trouver un second lien si les autre paste le propose 
Je trouve cela **REVOLUTIONNAIRE ! ! !** 
Tout mon respect pour le boulot accompli ;)
C'est le meilleur couplage Vstream / U2P qu'il puisse exister
Avant j'etais sur le loggins de Vstream pour uptobox, de la je devais utiliser osmosis (mais en le modifiant) pour acceder correctement à mes films mais la.....
**Grandiose ! ! !**

**Comment by noway80** [comment]
Version 0.9.7 en ligne

**Comment by sizanic** [comment]
Derrière cette grosse évolution, il y a aussi ces autres modifications : 
- Gestions des sous-dossiers (un seul niveau de sous-dossiers pour l'instant)
- Sablier de chargement et pagination par page de 20 pour les acteurs et les réalisateurs.


Par '_un seul niveau_' de sous-dossier, je veux dire par là : 
FILMS
.... Dossier1
........ Sous-Dossier1
.............Film1
.............Film2

Et il n'y a pas non plus la possibilité d'afficher des films qui serait dans le Dossier1 (car il existe un sous-dossier).

**Comment by noway80** [comment]
Beau boulot 
Mais on sort de la base , t avais insisté pour regroupé les liens et la tu autorises le meme film ou serie plusieurs fois
🤔

**Comment by sizanic** [comment]
@PassionFlix 
pourquoi avoir recréé une liste **_Agent 007_** alors que la saga **_James Bond 007_** existe déjà ?

Pour palier à un manque fonctionnel ?
Sais-tu que tu peux mettre une saga en marque-pages pour la retrouver facilement.

**Comment by PassionFlix** [comment]
Simplement parce que j'ai mis tous les films 007 hier soirs tard et que pour les retrouver dans mon interface uptobox c'est plus pratique mais ne t'inquiète pas grand chef😁 je vais ranger ça tout comme la saga planète des singes

**Comment by sizanic** [comment]
> Beau boulot
> Mais on sort de la base , t avais insisté pour regroupé les liens et la tu autorises le meme film ou serie plusieurs fois
> 🤔

oui, regroupé au sein du même paste.
Mais des pastes qui proviennent de personnes différentes qui ne se connaissent pas 🤔 

Et je n'ai pas dis que j'allais laisser comme ça 😄 
Cette première version peut être éprouvé pendant que j'essaye de l'améliorer.
Avoir le même film dispersé à plusieurs endroit d'une grande liste n'est pas l'idéal.

**Comment by noway80** [comment]
Parfait👍

**Comment by sizanic** [comment]
> Simplement parce que j'ai mis tous les films 007 hier soirs tard et que pour les retrouver dans mon interface uptobox c'est plus pratique mais ne t'inquiète pas grand chef😁 je vais ranger ça tout comme la saga planète des singes

OK, mais les ranger où ?
Tu n'a pas besoin de les classer.
Tu les jettes en vrac à la racine de tes films, tu les retrouveras dans la bonne saga, classer dans le bon genre, classé par résolution, etc. 😄

**Comment by sizanic** [comment]
alKODIque doit avoir son internet coupé vu qu'elle n'a pas encore réagit ici 🤔

**Comment by PassionFlix** [comment]
Oui oui, quand je dis ranger c'est mettre dans le dossier ou j'ai tous les films

**Comment by PassionFlix** [comment]
> alKODIque doit avoir son internet coupé vu qu'elle n'a pas encore réagit ici 🤔 
> 

Elle a du attaquer ses vacances par un marathon de sieste avec le peu qu'elle doit doit en temps normal

**Comment by PassionFlix** [comment]
@sizanic on me remonte un problème sur un utilisateur pour l'instant 

Avant la mise à jour de cet après-midi pas de soucis 
Avec la mise à jour, compte uptobox connecté aucun fichiers ne s'ouvrent "fichiers introuvable ", compte uptobox désactivé et ça fonctionne 
???

**Comment by sizanic** [comment]
Le sujet a été abordé ici : https://github.com/Up2Paste/Windows/issues/10

Il semblerait qu'après une mise à jour de beta, certains parametres sont à resélectionner.
Ou alors c'est que la beta ne s'installes pas comme il faut, il faut supprimer le dossier plutot que d'installer par dessus.

Et il me semble que le sujet à été abordé sur le [github de vStream](https://github.com/Kodi-vStream/venom-xbmc-addons/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)

**Comment by lebigboss** [comment]
Excellent cette évolution.
Juste dommage qu'on puisse pas voir la listes des pastes disponible dans le dossier, mais c'est déjà super d'avoir tout sur un endroit, simple et efficace.
Bravo et merci

**Comment by PassionFlix** [comment]
Merci siza

**Comment by sizanic** [comment]
> Juste dommage qu'on puisse pas voir la listes des pastes disponible dans le dossier

Déjà si tu essayes de rajouter un paste qui y est déjà il te le dit.
Concernant l'affichage de la liste des pastes (permettant une suppression individuelle), j'y pense 🤔

>mais c'est déjà super d'avoir tout sur un endroit, simple et efficace.
Bravo et merci

De rien, au plaisir.

**Comment by PassionFlix** [comment]
@noway80 U2P coupe l'extract en deux au dela de 500ko mais pour la mise a jour auto ca fonctionne comment ?

**Comment by noway80** [comment]
Dans le config tu renseignes , le idpaste aux film1 et film2

**Comment by PassionFlix** [comment]
film1 =
film2 =
serie1 =
serie2 =

illimité ?

**Comment by noway80** [comment]
U2p découpe tout les 500 ko environ,  après le config j ajouterai boucle si besoin
On verra car 2 pastes doit faire près de 8000 films

**Comment by PassionFlix** [comment]
Ou moins en multi liens comme moi tu peux quand même avoir que 4000 en 2 paste

**Comment by noway80** [comment]
Je pense que ta liste d acteur pese lourd , je m attendais jamais à une telle liste
Je pensais plus à une liste de favoris

**Comment by noway80** [comment]
Mais on peut faire autant de paste que besoin et comme siza a ajouté le multiliens 
Plus de limites

**Comment by PassionFlix** [comment]
Les favoris pour moi oui j'y est pensé mais la on parle de liste de partage donc je ne connais pas les favoris des autres utilisateurs 
D'où le fait que je rallonge les acteurs de plus en plus
Que tout le monde s'y trouve

**Comment by PassionFlix** [comment]
> Mais on peut faire autant de paste que besoin et comme siza a ajouté le multiliens 
> Plus de limites

Faudra revoir quand même le système de siza je pense mais il est sur la bonne voie

**Comment by noway80** [comment]
Mouais c est ta liste tu sais , c est déjà pas mal que tu la partages 
Pour les autres ils ont la recherche par acteur
Mais encore une fois c est ta liste , et tu la gères comme tu veux 😉

**Comment by PassionFlix** [comment]
D'ailleurs ça me fait penser à un truc...

@sizanic est-il possible d'avoir un index alphabétique dans la liste d'acteurs ?
(Quand on rentre dans Acteurs on ne soit pas direct sur les acteurs mais plus sur un index alphabétique, si je cherche un acteur à la lettre "V" vu la taille de ma liste j'ai pas fini de tourner des pages)
Simple supposition

**Comment by noway80** [comment]
Quand j en ai parlé à siza , d un groupe de paste par nom , c etait plus , un nom = un compte upto (avec tout les pastes de ce compte)
Le mélange de compte , de groupe et surtout de qualité comme ca brut sans filtre 
Siza va le faire évoluer,  mais à terme ce sera top
Apres personne n est obligé d ajouter des comptes externes aux siens, c est ca la liberté

**Comment by PassionFlix** [comment]
Moi j'adore mais dans ce cas si un lien est mort ou erroné comment sait on a quelle source il appartient pour en avertir le créateur ?

**Comment by noway80** [comment]
U2P pourrait gérer le mélange des comptes
Ne garder que le liens 
Et reformater,  group, acteurs , saga, qualité 
D autant plus que 90% des films doivent être en commun sur les listes
C est pas une demande 😁

**Comment by PassionFlix** [comment]
Oui c'est ça mais U2P n'a pas accès aux autres comptes que je vais ajouter au dossier FILMS sur vStream

**Comment by noway80** [comment]
Non mais le maître est le compte de celui qui le crée,  sur les autres tu ne récupères que les liens
Pas de liens morts si compte upto , tout ok ou tous hs

**Comment by noway80** [comment]
Moi je choisis un paste aussi sur le formatage du paste , évidemment sur la liste mais pas que 
Ya aussi ce que vous y apportez,  las gestion des groupes est vivante
Je conseillerais un compte plutôt qu un autre pour ça, le contenu est souvent similaire 
Et après c est des pastes spécialisés qui seront intéressants ou avec groupe spécialisé 
Enfin tu vois ça,  c est aussi mes choix 😉

**Comment by PassionFlix** [comment]
C'est sur qu'en comparaison, il vaut mieux le paste d'alko que le miens
Elle a fait un taf de fou sur les groupes

**Comment by noway80** [comment]
@PassionFlix 
Oui c'est ça mais U2P n'a pas accès aux autres comptes que je vais ajouter au dossier FILMS sur vStream

Pas besoin d acces aux comptes , c est le choix qui a été fait d etre fait en auto

Mais dans un multi compte , tu te retrouves avec une liste de numId tmdb
Tu peux imaginer une fenettre avec la liste des films d'un côté et le nom d un groupe de l'autre et tu bascules les films qui t interresse
Plus simple que de bouger dans les rep du compte , surtout si ta petite vignette du film
Tu vois tout est possible c est des choix .... 😁

**Comment by PassionFlix** [comment]
C'est surtout de savoir ce que le prog est capable de faire et ça seul les dev peuvent le savoir

**Comment by noway80** [comment]
Non j ai pas dit ça...car en fait je ne me sert pas de pastebin lol
Mais le peu que j ai regardé c est ca qui m a marqué 
C est vrai qu alko , ce qu elle fait est top et son compte est vivant comme un media

**Comment by noway80** [comment]
Non au niveau dev , rien de complexe.....😁

**Comment by PassionFlix** [comment]
Parle pour toi 🤪

**Comment by sizanic** [comment]
>U2P pourrait gérer le mélange des comptes

Avec passionflix on ne te suis pas.
Il faudrait que tu aies les identifiants des comptes uptobox de plusieurs personnes.
Je ne penses pas que tu puisses trouver plusieurs personnes qui te donnent accès à leur compte pour que tu lances U2P en multi-comptes pour tout rassembler 🤔 

Le rassemblement ne peut se faire que côté vStream.
Dans la source pastebin, il faut que le film n'apparaisse qu'une seule fois, mais que derrière on propose les liens de tous les pastes qui proposent ce film.
Je prévois une évolution dans ce sens.

**Comment by alKODIque** [comment]
> Non j ai pas dit ça...car en fait je ne me sert pas de pastebin lol
> Mais le peu que j ai regardé c est ca qui m a marqué
> C est vrai qu alko , ce qu elle fait est top et son compte est vivant comme un media

C'est gentil ça )
Suis a faire un groupe "Spécial Halloween"🎃 

Je m'amuse comme un enfant 😂🤣

EDIT:
Dire que je m'objectais a cette fonctionnalité au départ!! Pffft!!!

**Comment by sizanic** [comment]
>Dire que je m'objectais a cette fonctionnalité au départ!! Pffft!!!

oui, je m'en souviens, tu disais que tes listes tmdb te suffisait 😆 

>Suis a faire un groupe "Spécial Halloween"

Je voudrais tellement partager tes listes à ma communauté personnelle mais ils sont tous en version vStream officielle 😢 
J'ai raté la diffusion de la liste Chadwick Boseman, et maintenant je vais raté la liste Hallowen.
Il faut vraiment que ça sorte en officiel.

Il y a au moins la liste "Pandémie et contagion" qui sera toujours d'actualité lorsque ce sera dispo dans la version officiel 😆

**Comment by noway80** [comment]
lol on me comprend jamais
mais si u2p peut gerer
exemple
tu import x pastes films xxxx ,  yyyy  etc ..... , dedans tu as id et liens
1) tu regroupe les liens ( ca u2p le fais deja)
2) une fois que tu as cette liste totale
tu ouvres U2P graphique (depuis longtemps je pense qu il faut une interface graphique a plusieurs onglets)
tu imagines une fenetre avec d'un cote la liste de films avec une petite vignette du film et de l'autre une frame qui correspond a un groupe (plus facile que de deplacer dans des repertoires)
tu selectionnes et tu les bascules dans le groupe etc etc
3)tu choisis ta liste d'acteurs , de realisateur etc
4) tu recompiles et tu te retrouvres avec un multipaste entierement configuré pour toi  mais de plusieurs liste
tu te fous si c'est uptotox , 1fichier.... car pastebin gere plusieurs
l'important c'est le lien pas l'acces au compte et tu configures tout de l'exterieur   

suis je plus clair?

**Comment by alKODIque** [comment]
@sizanic 
J'y pense..
Je crois que j'ai lu qu'il était possible de gérer un sous-groupe a l'intérieur d'un dossier films, je pourrai en faire un peut-être de "Hommage à nos disparus " (genre)... Ainsi, Chadwick serait toujours présent 🤔 

Ayayaye, les idées ne cessent de germer 
🤯😁🤣

**Comment by sizanic** [comment]
c'est un exemple d'utilisation de sous-dossier, mais là je le trouve glauque.
Ce serait un dossier qu'avec des acteurs morts.

Tu avais créé le dossier pour Chadwick car c'est un dossier "D'actualité".
C'est ce qui est bien avec tes tes dossiers.
Mais en tant que dossiers d'actualités, il ne sont pas forcement amenés à être conservés.

**Comment by alKODIque** [comment]
@sizanic 
exactement pour les dossiers d'actualité, c'est mon objectif ;)

Et est-ce que tu crois que j'applique tout ce qui me passe par la tête?? loll 
Par chance que je ne le fais pas et par chance que je mentionne quasi jamais 😝

**Comment by sizanic** [comment]
> 1. tu regroupe les liens ( ca u2p le fais deja)
> 2. une fois que tu as cette liste totale
>    tu ouvres U2P graphique (depuis longtemps je pense qu il faut une interface graphique a plusieurs onglets)
>    tu imagines une fenetre avec d'un cote la liste de films avec une petite vignette du film et de l'autre une frame qui correspond a un groupe (plus facile que de deplacer dans des repertoires)
>    tu selectionnes et tu les bascules dans le groupe etc etc
>    3)tu choisis ta liste d'acteurs , de realisateur etc
> 3. tu recompiles et tu te retrouvres avec un multipaste entierement configuré pour toi  mais de plusieurs liste
>    tu te fous si c'est uptotox , 1fichier.... car pastebin gere plusieurs
>    l'important c'est le lien pas l'acces au compte et tu configures tout de l'exterieur
> 
> suis je plus clair?


Oui, c'est plus clair, tu as même mis trop de détails 😆 

Lorsque je parlais multi-comptes, je pensais à plusieurs comptes uptobox (de plusieurs personnes donc).
Alors que pour toi multi-comptes, c'est un compte uptobox, un compte 1fichier, etc. (d'une même personne).

Alors oui tu pourrais générer plusieurs pastes, un pour chaque compte.
Actuellement on utiliserait plusieurs fichiers cfg si on voulait le faire (et si il existait d'autres connecteurs 😄 ), donc on n'est pas gêné côté U2P.

Par contre côté vStream, je n'autorise pas le regroupement si le "HEBERGEUR=" est différent.

Donc la balle est dans mon camp.

**Comment by noway80** [comment]
Lol non tu groupes plusieurs comptes via les pastes de chacun
Tu regroupés tout , et tu appliques de l exteieur une personnalisation sans limite
Et à la fin tu Recrées des paste du groupement mais personnalisé 
Meme une personne sans compte uptobox pourrait récupérer les pastes et se faire sa propre vidéothèque personnalisé 
Punaise je pensais parle français 🤪😜
Suis belge ce ci explique cela 

En gros tu groupes liste  d alko et passion
Et alko personnalise la totalité,  car elle a accès à tout

**Comment by noway80** [comment]
Je pensais que vstream affiche plus liens upto etc ..
On peut pas mélanger, pourtant dans les 1ère paste yavait de tout en hebergeur

**Comment by sizanic** [comment]
> Lol non tu groupes plusieurs comptes via les pastes de chacun
> Tu regroupés tout , et tu appliques de l exteieur une personnalisation sans limite
> Et à la fin tu Recrées des paste du groupement mais personnalisé
> Meme une personne sans compte uptobox pourrait récupérer les pastes et se faire sa propre vidéothèque personnalisé
> Punaise je pensais parle français 🤪😜
> Suis belge ce ci explique cela


AAaah ,ca y est j'ai compris.

Tu n'accèdes pas aux **_compte_** des autres, mais tu accèdes aux **_pastes_** des autres.
Et à partir des pastes des autres tu mélanges tout pour te faire tes propres dossiers et recréer un nouveau paste personnalisé.

Je trouve que ce serait beaucoup de boulot sans être sûr que ce soit utilisé.
Peut-être faire une étude de marché avant 😆

**Comment by sizanic** [comment]
> Je pensais que vstream affiche plus liens upto etc ..
> On peut pas mélanger, pourtant dans les 1ère paste yavait de tout en hebergeur

Si, un paste peux avoir des mélanges. Je ne parlais pas des mélanges mais des regroupement de pastes.

Je dis qu'on ne peut pas regrouper des pastes si dans la ligne d'entete HEBERGEUR est différent.
Paste1 avec  : HEBERGEUR = www. upto box/
Et paste 2 avec HEBERGEUR = www. monsite.fr/

=> Là on ne peut pas regrouper.

Mais on peut regrouper ces deux pastes (qui contiennent des mélanges d'hébergeur) : 

Paste1 : 
```
TITLE; HEBERGEUR
film1; uptobox.com/sdfdsf
film2; 1fichier/sdfsd
```

Paste2 :
```
TITLE; HEBERGEUR
film1; monsite.fr/13213
film2; 1fichier/89798

```

**Comment by noway80** [comment]
Ben si tu mets hebergeur =""
Les liens garde leur hebergeur et tout passe, quand tu reconstruits
La place que ça prend n est plus problème desormais

**Comment by noway80** [comment]
C est du boulot oui au début mais après beaucoup moins dans les connecteurs qui arriveront car tu n as besoin que de la liste des liens 
La personnalisation et la gestion sera standard , en fait plus yaura de connecteur plus il sera intéressant d avoir cette approche

**Comment by sizanic** [comment]
> Ben si tu mets hebergeur =""
> Les liens garde leur hebergeur et tout passe, quand tu reconstruits

oui, c'est une bonne solution 👍 

Mais d'abord je voulais regarder un peu si je pouvais retrouver le bon hebergeur du paste qui correspond au film.
Mais si j'y arrive pas, on retirera la fonctionnalité _HEBERGEUR=_

**Comment by noway80** [comment]
On le laisse , car sinon faudra mettre des espaces partout , la misère 
En plus si ya une vérif d un paste par pastebin.com, c est plus discret
Tu sais si j ai seul sur ce projet,  j aurais crypté les données

**Comment by sizanic** [comment]
OK, du coup, je vais essayer de rattacher les bouts de mon coté pour le multi paste.

**Comment by noway80** [comment]
t en penses quoi de, passer en virtuel pour la personnalistaion et de passer U2P de script a logiciel avec interface ? 

 

 

 

 

> Message du 07/10/20 18:21
> De : "sizanic" 
> A : "Up2Paste/Windows" 
> Copie à : "noway80" , "Mention" 
> Objet : Re: [Up2Paste/Windows] [EVOLUTION] - Regrouper des liens pastes (#15)
> 
>
>

> OK, du coup, je vais essayer de rattacher les bouts de mon coté pour le multi paste.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/Up2Paste/Windows/issues/15#issuecomment-705046974", "url": "https://github.com/Up2Paste/Windows/issues/15#issuecomment-705046974", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by sizanic** [comment]
>passer U2P de script a logiciel avec interface

je ne suis pas convaincu de cette évolution si c'est pour la personnalisation (des dossiers, des acteurs, etc.).
Le résultat actuel, une fois rapatrié dans vStream, est largement suffisant.

Par conte une interface logiciel pour la config, pourquoi pas.
Certains utilisateurs sont rebutés à modifier un fichier de config à la main.

**Comment by noway80** [comment]
C est ce qui fait la différence dans les listes c est la personnalisation 
On réfléchit .....

**Comment by sizanic** [comment]
oui, on réfléchit, on échange.

Mais lorsque je vois déjà la personnalisation de alKODIque, et qui n'a même pas encore utilisé de sous-dossiers !

**Comment by sizanic** [comment]
Bon, il faut qu'on regarde aussi les autres issues, il y en a 13 !

**Comment by noway80** [comment]
Oui clair , dans mon esprit ça sera plus puissant et plus simple 
Imagines toi alko a la tête d une base 10000 films pour faire une personnalisation !!!

Ben elle dort plus !!!😁😁😁🤪

**Comment by sizanic** [comment]
je ne rejette pas l'idée.
(De toute façon tu serais seul pour ce dev)

Mais si personne derrière ne se sent le courage de prendre en charge ces manipulations 🤔

**Comment by noway80** [comment]
On réfléchit...on est pas pressé

**Comment by alKODIque** [comment]
> Oui clair , dans mon esprit ça sera plus puissant et plus simple
> Imagines toi alko a la tête d une base 10000 films pour faire une personnalisation !!!
> 
> Ben elle dort plus !!!😁😁😁🤪

Déjà que je ne suis pas l'être humain ayant le plus d'heures de sommeil à son actif 😂😂😂

Amenez-en des listes!!! 😝

**Comment by noway80** [comment]
On est d accord que la personnalisation serait extérieur y compris pour son propre compte, pas 2 systèmes

T en pense quoi alko ?

**Comment by alKODIque** [comment]
@sizanic @noway80 
Si je peux me permettre une opinion personnelle, jaime bien avoir le choix des pastes que j'utilise.

En fait, c'est ce qui fait la "beauté " de la source pastebin pour moi. Elle n'est pas une giga base de données comme les autres sources. Nous pouvons choisir le contenu voulu et évoluer dans nos idées créatives.

Si il y a regroupement de tout, je souhaite que ce soit une option... (que je n'utiliserai pas)

**Comment by noway80** [comment]
C est forcément une option, 
Je réfléchis ya beaucoup d avantage à une interface graphique

**Comment by alKODIque** [comment]
Je fait un EDIT ici...
Et ya danger aussi avec un regroupement: c'est que ceux qui donnent leur sources en partage ne voient plus la nécessité d'alimenter... Ils se diront: Bahhh! ya déjà tout plein alors pas besoin ! et ça risque de mourir dans le temps 

EDIT de mon EDIT:
Mais c'est juste mon avis perso hein! Ça veut pas dire dutout que j'ai raison ;)

**Comment by noway80** [comment]
Le risque existe deja,

**Comment by alKODIque** [comment]
je suis d'accord mais pas autant...

Présentement , on peut se voir en "complément" (les fournisseurs)

**Comment by noway80** [comment]
Lol c est le même,  les pastes proposés sont de qualité 
Pourquoi certains iraient  s embeter
Par contre de mélanger des pastes sans filtres , avec des qualités,  des erreurs de scan etc , denature la qualité du paste d origine
Ca me gêne ca , pour ça que je voulais U2P gere ca , par des filtres , il est plus adapté à ca

**Comment by noway80** [comment]
Suis pas à la recherche de boulot,  j en ai plein mais bon vous m avez donné le virus de la qualité 🤪

**Comment by alKODIque** [comment]
pour ça vraiment! U2P c'est la clé: j'essaie de trouver la façon de le présenter pour que les gens le voient aussi clairement que moi 🤔

J'y arriverai, j'y arrive toujours 🤓

**Comment by noway80** [comment]
Siza a raison , l avantage d une interface graphique est prépondérante dans l approche

**Comment by alKODIque** [comment]
> Suis pas à la recherche de boulot, j en ai plein mais bon vous m avez donné le virus de la qualité 🤪

Je le dit souvent: le Diable se cache dans les détails 😈👿 
Et le génie également 😬

EDIT: parlant de boulot... faut je m'y remette hehe

**Comment by sizanic** [comment]
Alors je n'étais pas dispo pour faire avancer le débat, mais alKO a très bien exprimé ce que je pense 😄 
- ça incitera moins les gens à partager.
- gérer soi-même ses regroupements est, je pense, pour beaucoup plus convivial que de prendre des méga listes toutes faites.


La version actuelle de  U2P apporte déjà beaucoup de fonctionnalités.
Travaillons maintenant un peu plus sur la forme que sur le fond.

On reviendra apporter de nouvelles fonctionnalités plus tard.
Pour la forme, il y a en effet le côté configuration comme je le proposais.

Et il y a un autre sujet à réfléchir.
Quelqu'un demandait comment faire pour avoir toujours la dernière version.

**Comment by noway80** [comment]
Je travaille sur 1fichier , mais les restrictions sont plus sévères que upto, mais ça va le faire

Pour mise à jour git ne suffit pas donc....

J ai vu que les personnes ne savait pas forcément ce qu il fallait conserver ou remplacer 
Je peux faire :
1) un zip installation de base
2) pour mise à jour, un zip qui ne contient que ce qui est à remplacer donc il extract dans le répertoire de base, en général  c est zip dans le build

Je les mets sur un dossier publique upto ou autre , on en est pas encore à maj auto

**Comment by sizanic** [comment]
ne fais rien pour l'instant, deux zip ça va embrouiller.
c'est juste un sujet pour y réflechir.

>on en est pas encore à maj auto

Parce que ce serait envisageable ?

**Comment by noway80** [comment]
Mais tu vois 1fichier on peut faire une extraction globale , 1 fois par heure, les rep 1 toutes les 30s
Donc si toute la personnalisation était extérieur,  j etais tranquille 
C est quand même a réfléchir,  tout n est pas comme upto

**Comment by noway80** [comment]
Oui envigeasable 
U2p interrogé un serveur chez moi par exemple, si new version on indique en popups d aller sur le git,  c est une étape
Apres on peut télécharger automatiquement la new version , et je fais un sfx, un installateur
Et c est réglé

**Comment by noway80** [comment]
Donc plus besoin du git presque

**Comment by alKODIque** [comment]
Question / Réflexion 

Ça serait fun avoir la possibilité de créer des listes d'épisodes ... Genre: 

- Les Meilleures épisodes d'halloween (ex)
- sélection d'épisodes à thème spécifique provenant de diverses séries 
- Les épisodes cultes de "How I met your mother" (ex)
- Etc, vous voyez le genre?

Est-ce envisageable ou bien je rêve en couleur ? 🤓

**Comment by noway80** [comment]
Réfléchis si je part sur une mise à jour semi automatique 
1)si new version
2) téléchargement auto
3) installation par user
Ou
1)si new version
2)popups indiquant d aller sur le git
3) l user gere

**Comment by noway80** [comment]
@alKODIque 
Tout est possible,  mais des choix à faire
Les connecteurs,  la personnalisation....

Lol t es incroyable

**Comment by alKODIque** [comment]
J'aime bien l'idée  qu'il y ait encore de l'espace dans notre tiroir à projets 🤓

Ça conserve l'esprit alerte et motivé 😝

**Comment by sizanic** [comment]
oui 😄 
Mais un projet à la fois.

>Tout est possible, mais des choix à faire
Les connecteurs, la personnalisation....

Il n'y pas de choix à faire, tu as commencé le connecteur, termine-le.

>Mais tu vois 1fichier on peut faire une extraction globale , 1 fois par heure, les rep 1 toutes les 30s
Donc si toute la personnalisation était extérieur, j'etais tranquille

Pour personnaliser à l'exterieur, il te faut le pastebin qui contient l'extraction du compte 1fichier.
Donc il te faut finir le connecteur.

A moins que cette extraction ne soit pas lié au connecteur 🤔

**Comment by sizanic** [comment]
> Ça serait fun avoir la possibilité de créer des listes d'épisodes ... Genre:
> 
> * Les Meilleures épisodes d'halloween (ex)
> * sélection d'épisodes à thème spécifique provenant de diverses séries
> * Les épisodes cultes de "How I met your mother" (ex)
> Est-ce envisageable ou bien je rêve en couleur ? 🤓


Il y a ici un sujet à propos de la création de dossiers pour les séries : 
https://github.com/Up2Paste/Windows/issues/8

Si ce sujet avance, il pourrait permettre de créer un dossier, tu y mettrais dedans des copies d'épisodes que tu veux centraliser.

Je te propose de copier/coller ta question dans l'autre issue pour qu'on ne la perde pas de vue lorsqu'on avancera sur le sujet

**Comment by PassionFlix** [comment]
Re la famille,
Possibilité de regrouper paste films et paste series

**Comment by sizanic** [comment]
> Possibilité de regrouper paste films et paste series

https://github.com/Up2Paste/Windows/issues/15#issuecomment-704219300

**Comment by PassionFlix** [comment]
> > Possibilité de regrouper paste films et paste series
> 
> https://github.com/Up2Paste/Windows/issues/15#issuecomment-704219300

?

**Comment by sizanic** [comment]
clique sur le lien la lumière sera 😄

**Comment by PassionFlix** [comment]
Je le connais ton post j'ai été sur le coup des la première minute que tu as posté mais tu ne précise pas si on peut mélanger les genres de paste 
Films 
Series
Anime
Et j'ai testé mon paste film et le paste série de Julie et ça fonctionne

**Comment by sizanic** [comment]
>Je le connais ton post j'ai été sur le coup des la première minute que tu as posté

Je sais bien et c'est pour ça que je suis étonné que tu poses la question.


> mais tu ne précise pas si on peut mélanger les genres de paste

je pensais pourtant avoir été clair 🤔 

![image](https://user-images.githubusercontent.com/47307622/95398144-54f8a580-0905-11eb-8c4d-d3f33e20865d.png)

**Comment by sizanic** [comment]
>Je dis qu'on ne peut pas regrouper des pastes si dans la ligne d'entete HEBERGEUR est différent.

> On le laisse , car sinon faudra mettre des espaces partout , la misère

> OK, du coup, je vais essayer de rattacher les bouts de mon coté pour le multi paste.

ça y est j'ai trouvé la solution, on peut regrouper des pastes qui ne sont pas sur le même hebergeur

On peut regrouper : 
Paste1 avec HEBERGEUR = www. upto box/
paste2 avec HEBERGEUR = www. monsite.fr/
paste3 avec HEBERGEUR = "" (tous les liens en dur dans chaque film)

**Comment by sizanic** [comment]
On peut regrouper tout avec tout dans la dernière version 😄
