### ISSUE TITLE
Comment faire un pastebin depuis un compte 1fichier

### ISSUE THREAD

**Issue by KoRnEr007** [Up2Paste/Windows#16]
Bonjour,
j'aimerai savoir si l'on peut utiliser 1fichier pour pastebin au lieu de uptobox, voir un mélange des deux.

Cdt
Jon

**Comment by PassionFlix** [comment]
Salut, il me semble que tu peux oui en modifiant la section fournisseur et en précisant bien ton api dans key , tu as essayé ?

**Comment by KoRnEr007** [comment]
Non pas encore

**Comment by KoRnEr007** [comment]
linkFolderFilm par contre la .....

**Comment by PassionFlix** [comment]
Essai alors pour commencer et je pense que @noway80 pourra ensuite te guider si j'ai vu faux (oui ça m'arrive souvent)

**Comment by PassionFlix** [comment]
> linkFolderFilm par contre la .....

Tu laisse vide si tu mets l'option stockage sur 2

**Comment by KoRnEr007** [comment]
Non des que je lance ca se coupe

**Comment by PassionFlix** [comment]
Tu as bien la dernière version?

**Comment by KoRnEr007** [comment]
yes mise a jour hier

**Comment by PassionFlix** [comment]
Que te dis le fichier activity.txt du dossier build?

**Comment by noway80** [comment]
Pas de connecteur 1fichier
Si t es d accord on peut le  creer ensemble

**Comment by KoRnEr007** [comment]
Si ca peut aider le communauté oui bien sur

**Comment by PassionFlix** [comment]
Bon ben désolé, encore une fois j'ai dis une connerie 
Je vais arrêter de parler je crois 😶

**Comment by noway80** [comment]
Super je reviens vers toi

**Comment by KoRnEr007** [comment]
je t'ai PM sur discord

**Comment by noway80** [comment]
@KoRnEr007 
[python36.zip](https://github.com/Up2Paste/Windows/files/5349322/python36.zip)
a mettre dans le rep build et remplacer existant


[makePastebin.zip](https://github.com/Up2Paste/Windows/files/5349354/makePastebin.zip)
c'est le nouveau config, dezip
mettre ta key 1fichier 
ne pas mettre url
j'ai mis ton rp FILMS_UHD

**Comment by noway80** [comment]
[exe.win-amd64-3.6.zip](https://github.com/Up2Paste/Windows/files/5349457/exe.win-amd64-3.6.zip)

**Comment by noway80** [comment]
https://www.transfernow.net/jECbQe102020

**Comment by noway80** [comment]
https://www.transfernow.net/y6RYg6102020

**Comment by sizanic** [comment]
Je viens de voir le paste 

Vous n'avez pas mis le préfixe pour l'hébergeur ?
`URLS=https:// 1 fichier . com/?`

mais je crois que c'est à toi @KoRnEr007 de le mettre dans la conf.

**Comment by noway80** [comment]
Non c est moi , car extraction est différente de upto  , pour allez vite j ai mis comme ca
La version suivante je corrigerai

**Comment by sizanic** [comment]
Mais du coup, ce parametre est-il utilisé ? 

```
[Fournisseur]
url = https://monHebergeur.com/
```

**Comment by noway80** [comment]
Oui
Je vais ajouter nbFormat
Et activer url = http 1fichier...

**Comment by noway80** [comment]
0.9.8
Url = 1fichier....
Scan format ok

**Comment by KoRnEr007** [comment]
je ne vois pas ton zip :)

**Comment by noway80** [comment]
C est sur le git

**Comment by Up2Paste** [comment]
Traité !
