### ISSUE TITLE
Questions Scan U2P

### ISSUE THREAD

**Issue by PassionFlix** [Up2Paste/Windows#17]
Quels réglages, pour quels types de contenu

**Comment by PassionFlix** [comment]
J'ai des dessin animé de type goldorak ou autre, en quoi dois je les scanner ?
Series ou anime?

**Comment by alKODIque** [comment]
@PassionFlix 
j'ai inclu Goldorak dans Anime et ça a bien fonctionné :)

**Comment by PassionFlix** [comment]
Ok super merci @alKODIque 
Jusqu'à présent je n'ai fait que du film donc comment faire les animes au niveau uptobox ?
Groupe 00_
Dossier et sous dossier?

**Comment by sizanic** [comment]
> J'ai des dessin animé de type goldorak ou autre, en quoi dois je les scanner ?
> Series ou anime?

La différence entre séries et animes, c'est juste pour la recherche tmdb.
Avec le type **_Anime_**, la recherche se fera exclusivement sur des séries de type "Animations" dans TMDB.
Avec le type **_Serie_**, pas de filtre spéciale.

Du coup Goldorak en recherche Série aurait fonctionné aussi car il n'y pas de série "non animés" qui s'appelle Goldorak.

**Comment by sizanic** [comment]
> comment faire les animes au niveau uptobox ?
> Dossier et sous dossier?

La gestion des sous-dossiers n'est pas encore présente dans U2P.

Il y a un sujet de type Évolution ici : https://github.com/Up2Paste/Windows/issues/8

Mais la création **_"manuelle"_** de l'arborescence peut fonctionner avec vStream.
Comme ce que vous avez fait pour les films ( qui n'est à terme pas la bonne méthode) : 
`00_Dossier1:Sous Dossier`

**Comment by PassionFlix** [comment]
Donc je peux faire 
01_Goldorak (je prend 01 car 00 c'est mes films)
.....fichiers classés de type 1x01 1x02 ....
01_Inspecteur Gadget
.....fichiers classés de type 1x01 1x02....

**Comment by PassionFlix** [comment]
> `00_Dossier1:Sous Dossier`

Sous dossier étant les saisons par exemple

**Comment by sizanic** [comment]
non 😆 
ne mets pas de préfixe pour les séries en général.

Pour les séries, la gestion des séries/saisons est native 

```
SERIES
....Goldorak
........Saison01
.............1x01 1x02
........Saison02
.............2x01 2x02
....Inspecteur Gadget
........Saison01
.............1x01 1x02 
........Saison02
.............2x01 2x02 

```

si tes fichiers sont bien nommées SxE, tu_ n'es pas obligé de faire les dossiers pour les saisons, c'est supporté : 

```
SERIES
....Goldorak
.........1x01 1x02.........2x01 2x02
....Inspecteur Gadget
.........1x01 1x02 .........2x01 2x02 

```

Je pensais que tu voulais faire plusieurs niveaux de sous-dossiers.

Voir également ici : [TUTO U2P](https://github.com/Up2Paste/Windows/wiki/TUTORIAL-Up2Paste)

C'est le seul paragraphe qui est noté deux fois (première page et dernière page) : 

`Sur votre compte Uptobox, les épisodes doivent être dans un dossier qui porte le nom de la série. Il est conseillé de mettre l'année de la série dans le titre de ce dossier, ex : Flash (2014) afin d'éviter les erreurs sur les doublons. Dans le dossier de la série, vous pouvez soit créer un dossier par saison, soit déposer les épisodes de toutes les saisons, mais en respectant une syntaxe : S01E01.`

**Comment by PassionFlix** [comment]
Ok j'ai compris (normalement lol)
Tu connais ma faculté à apprendre très vite quand on m'explique longtemps 😂
