### ISSUE TITLE
Affichage de la résolution des films (ffprobe)

### ISSUE THREAD

**Issue by alKODIque** [Up2Paste/Windows#18]
Bonjour :)

 @noway80  @sizanic

Dans le dossier ''Résolution'', l'ordre d'affichage proposé est présentement:

- HD (1080p)
- 480p
- 4K (2160p)
- SD (720p)
- Indéterminé

Esthétiquement (évidemment 😝) et logiquement aussi, je propose de modifier ainsi:

- 4K (2160p)
- HD (1080p)
- HD (720p) - et non pas SD
- SD (480p)
- Indéterminé

Qu'en pensez-vous ?

**Comment by PassionFlix** [comment]
J'en pense que du bon 😉 mais c'est pas à moi que tu proposais 😂

**Comment by noway80** [comment]
C est sur vstream, ca avait été déjà évoqué je crois

**Comment by sizanic** [comment]
J'ai déjà changé le SD720 en HD chez moi, ce sera dans la prochaine mise à jour.
Pour l'ordre, faut que je vois, pour l'instant c'est l'ordre alphabétique. Je dois forcer l'ordre alors que je ne sais pas quelles seront les résolutions disponibles.

**Comment by noway80** [comment]
480p, 720p, 1080p, 4k

**Comment by alKODIque** [comment]
> J'ai déjà changé le SD720 en HD chez moi, ce sera dans la prochaine mise à jour.
> Pour l'ordre, faut que je vois, pour l'instant c'est l'ordre alphabétique. Je dois forcer l'ordre alors que je ne sais pas quelles seront les résolutions disponibles.

je crois que j'ai déjà vu du SD 530p et mobile 360p (qui j'espère ne sera pas proposé 😆)

**Comment by sizanic** [comment]
Dans la dernière Beta 👍 

@alKODIque 
le sujet peut être cloturé si tu es d'accord avec la modif en place.
