### ISSUE TITLE
Problème extraction Séries

### ISSUE THREAD

**Issue by toadnam** [Up2Paste/Windows#2]
Bonjour,

je commence avec pastebin et je voudrais savoir où ca bloque svp.
J'ai un compte uptobox, un dossier SERIES et dans ce dossier il y a 13 épisodes la 1ère saison de The Listener.
voici mon fichier makePastebin :

[Config]
lang = fr
name = Moncompte
certification = 16
nbFormat = 50

[Extract]
serie = 1
film = 0
anime = 0
linkFolderFilm =
stockage = 2
modeTMDB = 0

[keys]
keyMovieDB = token que j'ai récupéré sur le site TMDB
keyUpto = token que j'ai récupéré sur le site uptobox

[Fournisseur]
url = https://uptobox.com/

[RepDistant]
serie = SERIES
film = FILMS
anime = ANIME
groupe = REP_

[Logger]
niveau = info
#info ou debug

voici mon fichier activity : 
27-09 19:02:26 :: MakePastebin.Main :: INFO :: Extraction Serie
27-09 19:02:26 :: MakePastebin.UptoToPastebin :: INFO :: Effacement table Group: serie
27-09 19:02:26 :: MakePastebin.Main :: INFO :: Extraction Compte Uptobox
27-09 19:02:27 :: MakePastebin.Uptobox2 :: INFO :: Folder://SERIES nb files: 20 extrait:13
27-09 19:02:27 :: MakePastebin.CatSerie :: INFO :: Pastebin Series Crees
27-09 19:02:27 :: MakePastebin.Main :: INFO :: U2P 0.9.2c (utopie) exporte fichier d'un compte Uptobox => vStream

voici mon fichier extractSerie_Moncompte :
CAT;TMDB;TITLE;SAISON;GROUPES={"R":"Réalisateurs","D":"Diffuseurs"};YEAR;GENRES;URLS=ht tps:// uptobox.com/

J'ai du louper une étape quelque part... Mais ou? aucune idée

**Comment by noway80** [comment]
Tu as un dossier serie c est la racine
En dessous tu dois avoir des dossiers avec le nom des series example  dexter
Dans ce dossier tu mets tous les episodes de dexter

Tu as fait comme ca ?

**Comment by benking110181** [comment]
salut essaye en créant un dossier The Listener avec l'année dans ton dossier series et copies les fichier dedans et réessaye

**Comment by noway80** [comment]
Si je lis bien , tu crees un répertoire the liste
Et tu mets tesepisodes dedans
Tu rescan et ça devrait être bon
Lol trop tard🤪

**Comment by toadnam** [comment]
non j'avais mis juste les 13 épisodes dans le dossier SERIES, je vais créer un dossier The Listener (2009) et mettre les épisodes dedans et je vous dis

**Comment by benking110181** [comment]
déjà pour être sur du titre de la série va voir sur tmdb car the listener il y en a 2 avec des années différentes

**Comment by toadnam** [comment]
Yes j'ai eu une fenêtre qui s'est ouverte et qui m'a demandé quelle était la série... :-)

**Comment by noway80** [comment]
Il est en mode zéro,  donc il aura le choix

**Comment by toadnam** [comment]
impeccable, cela a fonctionné merci

**Comment by toadnam** [comment]
en tout cas merci beaucoup pour votre rapidité, c'était simple et efficace. Au top!

**Comment by sizanic** [comment]
De rien,
Et surtout n'oublie pas de partager tes pastes 😄

**Comment by toadnam** [comment]
Oui bien sur mais pour l'instant il y a qu'une série 😂

**Comment by noway80** [comment]
T as connu comment le pastebin?

**Comment by toadnam** [comment]
Via un groupe fb, et une passionnée canadienne qui est super sympa et qui donne envie de s'intéresser à kodi plus en profondeur.

**Comment by noway80** [comment]
On voit qui😉

**Comment by sizanic** [comment]
Oui, on voit très bien qui c'est ❤️

**Comment by alKODIque** [comment]
Ha Ha Ha  
Il y avait mon petit doigt qui me disait de venir jeter un oeil par ici, je me suis senti interpellée et heureuse de voir qu'il ne s'agissait en rien du côté noir de la force :p

**Comment by toadnam** [comment]
Non non du tout bien au contraire. Moi C'est Gaël au fait 😉

**Comment by alKODIque** [comment]
> Non non du tout bien au contraire. Moi C'est Gaël au fait 😉

Ha! je vois :)
Heureuse de te retrouver sur Github ;)

**Comment by toadnam** [comment]
Pas mal ton pseudo qui montre que tu es accroc à kodi 😂
