### ISSUE TITLE
Incohérence jaquettes

### ISSUE THREAD

**Issue by PassionFlix** [Up2Paste/Windows#20]
J'ai remarqué une incohérence entre le film scanner et validé par U2P "Driven de 2001" et la jaquette dans vstream ne correspond pas
D'où vient le problème ?

**Comment by sizanic** [comment]
En effet, certains films voient leur jaquette écrasé par un film du même nom.
Également vu avec le film "1987".

**Comment by PassionFlix** [comment]
1987 le film de 2014, celui avec une VHS en photo ?
Parce que moi il est bon celui la

**Comment by sizanic** [comment]
Il est bon tant que tu ne va pas voir le détail d'un autre film qui s'appelle également 1987.
Les infos de ce film viendront écraser les infos du premier film.

**Comment by PassionFlix** [comment]
Cela se joue un peu sur du cache qui resterait chargé sur les mauvaises infos?

**Comment by sizanic** [comment]
Problème de cache en effet, les infos s'écrasent entre elles, il n'y a qu'une seule ligne en base pour le film 1987.
Je vais regarder ...

**Comment by PassionFlix** [comment]
Faudrait vider la mémoire tempon ou le cache je sais pas trop les différencier a chaque changement de position du curseur

**Comment by alKODIque** [comment]
Seulement vider le cache ne fonctionne pas. même effacer complètement les bd de vstream, le dossier temp de kodi et le simple cache, ça ne fonctionne pas non plus 🤷🏻‍♀️

**Comment by sizanic** [comment]
C'est corrigé.
Vider le cache vStream après installation de la Beta.

Ce n'était pas un problème d'écrasement de données.
On ne cherchait pas en fonction de l'année, ni même par l'ID TMDB 🤔

**Comment by PassionFlix** [comment]
Je teste de suite

**Comment by PassionFlix** [comment]
YESSSS c'est bon pour moi
@alKODIque ca donne quoi chez toi ?

**Comment by alKODIque** [comment]
J'installe d'ici 30 minutes :)

**Comment by alKODIque** [comment]
Parce que dans 30 minutes, @sizanic aura bien fait 3 ou 4 autres versions hein! 🤣

**Comment by sizanic** [comment]
J'en suis déjà à 2 versions 🤣 

- Correction pour les films aléatoires, parfois plus de boutons "suivant".
- Correction bouton "Suivant" mais rien dans la page suivante.

**Comment by alKODIque** [comment]
Bah voilà! je savais bien! 😂😂😂

**Comment by PassionFlix** [comment]
Tu vas t'en sortir @sizanic  🤪

**Comment by alKODIque** [comment]
tout est bon pour moi également :)

**Comment by sizanic** [comment]
Ce sujet peut être cloturé 👍
