### ISSUE TITLE
Titre avec caractères spéciaux

### ISSUE THREAD

**Issue by sizanic** [Up2Paste/Windows#22]
Il y a un problème avec cette ligne :

```
CAT;TMDB;TITLE;SAISON;GROUPES;CAST;DIRECTOR;NETWORK;YEAR;GENRES;RES;URLS=ht tps:// uptobox.com/
anime;73114;Steins;Gate 聡明叡智のコグニティブ・コンピューティング;Episodes (P01);[];[];[];[];2014;[16, 10765];[];{"E001": "z5bs6djv5mxz", "E002": "bpfyuhpyzog3", "E003": "l9tmo6bkxk0l", "E004": "abw3mdcpq03g", "E005": "d79e4qvvshtr", "E021": "fm4xeccncp7l", "E022": "s9kjqob44plw", "E023": "rvaexk168nkv", "E024": "m290i6pqbcs2", "E025": "lt85j57fxdmn"}
```
Le problème n'est pas du tout les caractères asiatiques 😆 

=> c'est le point-virgule au début du titre : `Steins;Gate` 

Des solutions que je vois au niveau de U2P : 
- Mettre le titre entre guillemets : `"Steins;Gate  聡明叡智"`  
- Échanger le point-virgule par un autre caractère, par exemple une virgule : "Steins, Gate  聡明叡智"

Coté vStream je ne peux rien faire.

**Comment by alKODIque** [comment]
moi je retire complètement toute ponctuation lorsque j'ai un ennui et ça fonctionne. u2p trouve sans même me demander en mode tmdb 0

**Comment by alKODIque** [comment]
en fait, je crois qu'il n'y a aucun "scrapper" qui aime la ponctuation dans les titres ... ceux de kodi n'y font pas exception. D'ailleurs, à plusieurs egards, u2p est beaucoup plus juste que tmdb et tvdb du repo officiel de kodi

**Comment by noway80** [comment]
Je remplacerai ; par :
