### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by alKODIque** [Up2Paste/Windows#4]
@noway80 et probablement @sizanic
Je me posais la question:

Disons que j'ai l'idée d'ajouter un répertoire dans lequel j'inclurais des liens youtube de ma chaîne perso sur laquelle je publie des tutos pour mon groupe.  

(Ces liens seraient bien entendu  hébergés sur mon compte Uptobox)

Disons que ce pourrait être sous forme de liste :"Tuto kodi" parmi les listes de films ou  même une section séparée tels que Films,Séries, Animes puis Youtube, etc... Enfin quelque chose du genre.

Je sais qu'aucune information ne pourrait en être extraite via TMDb mais serait-il possible d'en extraire une vignette? - un peu comme fait une capture pour indiquer les chapitres d'un film?

(C'est pas pressé, ce n'est même pas dans mes projets pour l'instant mais  j'aimerais juste avoir une idée à savoir si ce serait envisageable)

Merci et A+

**Comment by sizanic** [comment]
Je ne prévois pas une section "Autres" ou "Youtube".
Tu peux prévoir un répertoire, voire même un pastebin dédié qui ne contient que tes vidéos tuto.

Mais ta question porte plus je pense sur la possibilité de faire la vignette, et là je ne vois pas comment je pourrais faire.
Pour un fonctionnement dynamique, pour générer l'image, il faudrait décrypté le lien uptobox, ce serait trop long pour tous les films d'un dossier.
