### ISSUE TITLE
> > un attribut qui accompagne certaines personnes qui, comme pré-requis, doivent posséder un cerveau 🤷🏻‍♀️

### ISSUE THREAD

**Issue by alKODIque** [Up2Paste/Windows#5]
> > un attribut qui accompagne certaines personnes qui, comme pré-requis, doivent posséder un cerveau 🤷🏻‍♀️
> 
> Attention, je connais l'admin de ce github, il pourrait te banir pour sexisme 🤔 😉

ou alors tu t'attaques à la nationalité en désignant les Français en général ?

_Originally posted by @sizanic in https://github.com/Up2Paste/Windows/issues/3#issuecomment-700816570_

holala...
je me relis et tu as raison 🙊
Je crois avoir atteint mon niveau d'incompétence côté humour malheureusement.

L'art de se mettre les pieds dans les plats par contre, je maîtrise à la perfection 😉

**Comment by alKODIque** [comment]
comment j'ai fait ça? quelqu'un peut retirer cette new issue svp?? suis désolée!!

**Comment by sizanic** [comment]
Alors toi aussi tu crées un autre sujet lorsque ça sort du contexte 😆 

T'en fais pas on l'a bien pris, on sait faire la différence entre de l'humour et de la connerie.

**Comment by alKODIque** [comment]
Oufff
Je suis rassurée 
:)))))
