### ISSUE TITLE
Liste réalisateurs

### ISSUE THREAD

**Issue by sizanic** [Up2Paste/Windows#6]
Sujet pour proposer des réalisateurs.

@alKODIque
Voici encore un bel oubli : 

M. Night Shyamalan

**Comment by alKODIque** [comment]
Lorsque j'ai vu le nom, j'avoue avoir eu besoin de googler.. Puis j'ai vu sa filmographie 😲 Et il y en a plusieurs qui font partie de ma sélection personnelle de "coup de coeur" !
Quelle inculte je suis 

EDIT: Tu as vu "Devil"?

**Comment by sizanic** [comment]
c'est pour cela que je t'ai interpellé, je sais très bien que c'est ton genre 😄 

Tiens c'est marrant, il n'y a pas longtemps j'ai mis Devil dans mes favoris pour le regarder prochainement, je ne savais pas que c'était lui.
(mais le film est vieux et je me demande si je l'ai pas déjà vu 🤔 ) mais à revoir de toute façon.

**Comment by alKODIque** [comment]
Une liste a moi:
https://www.themoviedb.org/list/7050253

Le film "Exam" entre-autre est une belle découverte ...

**Comment by sizanic** [comment]
J'avais repéré Exam déjà dans ta liste de films.
Je me le mets de côté du coup.

En parlant de tmdb, l'ajout du trie par Réalisateur va te donner du travail.

**Comment by alKODIque** [comment]
Faudra que je me mette a jour dans le progrès que vous avez fait alors car je savais pas que ça avait changé

**Comment by sizanic** [comment]
Regarde avec ce paste de test (réalisé a partir de ton compte), ce que ça va donner : 

Y9xuwnWs

**Comment by alKODIque** [comment]
@sizanic 
J'avais pas vu ton dernier message!
Je vois après mon travail sans faute!  puis je suis en congé demain alors je me colle à cette nouvelle version, j'ai bien hâte :)

**Comment by noway80** [comment]
Le mieux c est qu on fasse realisateur comme acteur ?

**Comment by sizanic** [comment]
- Sam Raimi

**Comment by sizanic** [comment]
> Le mieux c est qu on fasse realisateur comme acteur ?

Je ne suis pas encore très sûr de la meilleure solution 🤔

**Comment by noway80** [comment]
je rajoute ceux posté ici ?

**Comment by sizanic** [comment]
En attendant, ce serait sympa 👍🏻🤗

**Comment by noway80** [comment]
ajouté! dans la bd sur la version
plus qu a mouliner

**Comment by alKODIque** [comment]
@sizanic 
Voilà, ne reste plus qu'à supprimer le cache de vStream puis les informations pour les réalisateurs y seront !

J'ai aussi fait le travail (traduction pour la plupart) avec les acteurs et actrices de ma collection  🤓

Je m'attaques aux acteurs de la liste de @PassionFlix après mon dodo hihi

**Comment by alKODIque** [comment]
@noway80 
Suggestions de réalisateurs, puisque côté comédies, nous n'avons pas vraiment suggéré jusqu'ici:

- Gene Stupnitsky

- Seth Rogen

- Adam Sandler

- Whoopi Goldberg - ouiiiiiii une femme !!!! :P

**Comment by alKODIque** [comment]
Je suggère également 

Xavier Dolan
