### ISSUE TITLE
Arborescence des séries

### ISSUE THREAD

**Issue by sizanic** [Up2Paste/Windows#8]
>Pour série, si tu tombes sur un dossier "REP_", tu notes le nom et tu descends dans les sous-dossiers.
Ne cherche pas à regarder si il y des fichiers.
Dès que tu tombes sur un dossier sans le préfixe, c'est censé être un nom de série et tu reprends le scan normal.

Oui et non 
sous un groupe , toutes les series doivent y être a attache
Donc 00_
Donc on appelle tout les répertoires dans ce groupe
Et on scan n0 et n-1
Apres quand c est fini , tu reprend ta boucle initiale 

La ca demande une recurcivite .

_Originally posted by @noway80 in https://github.com/Up2Paste/Windows/issues/3#issuecomment-702188608_

**Comment by noway80** [comment]
Euh c est pourquoi faire le sujet?🤔

**Comment by sizanic** [comment]
Pour avoir des échanges dédiés à cette évolution.

**Comment by noway80** [comment]
Ah ok , toute façon,  on fait ?

**Comment by noway80** [comment]
Mais ya effectivement un intérêt pour films en tout cas
Disney
Super héros 
Etc...

Moins sur serie , en tout cas j en vois pas

**Comment by sizanic** [comment]
Prends ton temps c'est pas pressé.
Et en effet on peut faire d'abord pour film dans un premier temps.

**Comment by noway80** [comment]
J arriverai jamais à faire s4v , 😁

**Comment by sizanic** [comment]
> Prends ton temps c'est pas pressé.
> Et en effet on peut faire d'abord pour film dans un premier temps.

Dans un premier temps ne veut pas dire maintenant 😄

**Comment by noway80** [comment]
Oui mais serais bête d avoir des évolutions à remettre dans s4v, tout est top
On fait films et après je prend pause pour s4v

**Comment by noway80** [comment]
Folder://ANIMES/00_LongMetrages/00_A:Lego nb files: 7 extrait:7
Extrait log passionflix 
Ya arborescence 😁 donc film ça va le faire
