### ISSUE TITLE
Problème automatisation u2p pour pastebin

### ISSUE THREAD

**Issue by toadnam** [Up2Paste/Windows#9]
Salut tout le monde,

j'ai voulu mettre en place l'automatisation du copier-coller pour pastebin depuis u2p mais quand je lance u2p , voilà les erreurs que j'ai... :
Erreur : le processus "chromedriver.exe" est introuvable.
Erreur : le processus "chrome.exe" est introuvable.
[6920:15488:1002/103557.094:ERROR:media_history_store.cc(363)] Failed to create or update the media history store.

DevTools listening on ws://127.0.0.1:53013/devtools/browser/687b8512-6ceb-43ad-a4ee-8eac59e7c8d1
[6920:2888:1002/103558.829:ERROR:CONSOLE(1)] "Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'strict-dynamic' 'sha256-1+GSDjMMklBjZY0QiWq+tGupCvajw4Xbn46ect2mZgM=' 'sha256-2mX1M62Fd0u8q0dQY2mRsK5S1NS9jJuQAvyE8tD0dkQ=' 'sha256-EtIKSV82ixJHE3AzqhoiVbUGKG+Kd8XS0fFToow29o0=' 'sha256-QSyFltV9X3gkyBrg+SMfKvZNXmqPQc6K4B6OYhTuXmw=' 'sha256-ANdtIo91Yk/zh1YKZ+IXKP1pb00awOjEFMAUld02F6A=' 'sha256-CbH+xPsBKQxVw5d9blISLDeuMSe1M+dJ4xfArFynIfw=' 'sha256-lA+EURA/fC0TZq1ATYZvxIQHBc9iTAaBcI+dFMmTn9I=' 'sha256-r8M35L32RquDK8jFp/tROc74JLQUl2lsS/eNENiX+gw='". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
", source: chrome-search://local-ntp/local-ntp.html (1)

quelqu'un peut m'aider?

Merci d'avance

**Comment by PassionFlix** [comment]
Tu es sur quelle version de U2P ?

**Comment by PassionFlix** [comment]
Nous sommes a la V0.9.5.b en test

**Comment by toadnam** [comment]
j'ai pris la dernière mais j'ai réussi à trouver mon problème. Je vais l'expliquer pour les personnes qui tombent sur la meme erreur que moi...
Je suis allé sur https://chromedriver.chromium.org/downloads et j'ai pris la dernière version de  ChromeDriver 86.0.4240.22
Je l'ai mis dans le dossier pastebin et je l'ai lancé.
J'ai ce message dans la boite de dialogue ChromeDriver was started successfully.
et ensuite j'ai relancé u2p et la mise à jour s'est faite toute seule avec mon pastebin. :-)
Si cela peut aider d'autres personnes...
Merci en tout cas

**Comment by PassionFlix** [comment]
Peut être que cela mettra @noway80 sur une piste

**Comment by benking110181** [comment]
passionflix toi ca fonctionne maintenant 
essaye chromedriver ca peut expliuer ton probleme

**Comment by toadnam** [comment]
le seul truc c'est qu'à la fin il faut fermer la fenêtre u2p sinon on peut attendre longtemps lol

**Comment by benking110181** [comment]
oui mais ca te permet de voir si il y a eu des erreurs ou sinon tu va dans le dossier error

**Comment by Louis-Petit** [comment]
me voila

**Comment by Louis-Petit** [comment]
soyez indulgents stp je ne comprends rien à ce que vous dites, mais je fais des efforts lol

**Comment by benking110181** [comment]
louis-petit va la et essaye ca pour te connect a shield
ht   tps://support     .nvidia.    eu/hc/fr/articles/      115001071549-Comment-puis-je-partager-mon-r%C3%A9pertoire-SHIELD-avec-un-PC-
bien sur tu enleve espace

**Comment by Louis-Petit** [comment]
le fait d'être sur mac ne change rien?

**Comment by benking110181** [comment]
je ne conait pas ton experience mais tu connait smb

**Comment by Louis-Petit** [comment]
non je ne connais rien, vraiment je suis newbie... la marche est haute

**Comment by benking110181** [comment]
ht            tps://www                 .jessblog.fr/2016/08/08/acces-aux-dossiers-du-shield-depuis-un-pcmac/#.X3bww2gzbb0

**Comment by benking110181** [comment]
google est ton ami

**Comment by toadnam** [comment]
> oui mais ca te permet de voir si il y a eu des erreurs ou sinon tu va dans le dossier error

c'est pas faux :)

**Comment by benking110181** [comment]
il faut que tu remplace le dossier plugin.video.vstream ici par celui du zip beta 
Android\data\org.xbmc.kodi\files\.kodi\addons\plugin.video.vstream
attention avec maj beta par zip dans kodi sur android il copie pas tout les fichier c'est pour cela qu'il faut faire ca le bug a etait decouvert il y a pa slongtemp pour moi

**Comment by benking110181** [comment]
toadnam tout fonctionne pour toi tu a quel version

**Comment by benking110181** [comment]
version U2P

**Comment by toadnam** [comment]
0.9.5b

**Comment by toadnam** [comment]
> toadnam tout fonctionne pour toi tu a quel version

oui nickel, je continue de mettre à jour mes séries ;-)

**Comment by benking110181** [comment]
parfait! Tu a les acteurs et réalisateurs?

**Comment by benking110181** [comment]
a séries donc tu doit avoir les diffuseurs

**Comment by benking110181** [comment]
tu n' rien dans le dossier error ?

**Comment by toadnam** [comment]
> tu n' rien dans le dossier error ?

dans errorSerie rien du tout :)

**Comment by toadnam** [comment]
> a séries donc tu doit avoir les diffuseurs

diffuseur et genres

**Comment by Louis-Petit** [comment]
> il faut que tu remplace le dossier plugin.video.vstream ici par celui du zip beta
> Android\data\org.xbmc.kodi\files.kodi\addons\plugin.video.vstream
> attention avec maj beta par zip dans kodi sur android il copie pas tout les fichier c'est pour cela qu'il faut faire ca le bug a etait decouvert il y a pa slongtemp pour moi

alors, c'est interessant... dans or.xbmc.kodi j'ai files ou files.nv, mais dans les 2 cas les dossiers sont vides

**Comment by benking110181** [comment]
ce sont des dossier caché

**Comment by Louis-Petit** [comment]
et je n4ai pas de dossiers files.kodi

**Comment by benking110181** [comment]
element masqué sur windows

**Comment by benking110181** [comment]
Quatrième méthode pour afficher les fichiers cachés de la Bibliothèque sur Mac
Ouvrez Finder.
Aller dans Macintosh HD et appuyer simultanément sur les touches CMD + Maj + . ( point) sur le clavier.
Les fichiers cachés deviendront automatiquement visibles.
Appuyez à nouveau sur le même raccourci clavier pour les cacher.

**Comment by Louis-Petit** [comment]
les touches CMD + fn + Maj + . ( point) sur le clavier

**Comment by Louis-Petit** [comment]
donc maintenant, je des zip la version beta et je la glisse dans ce dossier en remplaçant les fichiers existant?

**Comment by benking110181** [comment]
oui

**Comment by benking110181** [comment]
il faut que tu remplace le dossier plugin.video.vstream ici 
Android\data\org.xbmc.kodi\files.kodi\addons\plugin.video.vstream par celui du zip beta

**Comment by Louis-Petit** [comment]
ça ne fonctionne toujours pas

**Comment by benking110181** [comment]
sur quel source ? ca fonctionnait avant

**Comment by Louis-Petit** [comment]
en fait tout fonctionnait nickel jusqu'à hier soir, j'utilise essentiellement pastebin avec tes codes, ceux d'Alko et de Passion, dans la nuit, impossible d'ouvrier vos pastes... ce matin je mets la version beta, je peux ouvrir de nouveau vos liens, mais... tous les fichiers sont en échec de lecture ou liens introuvables

**Comment by Louis-Petit** [comment]
ceux d'Alko

**Comment by benking110181** [comment]
moi ca fonction mes liens ca peut venir aussi de ton compte uptobox ou ton debrideur si tu en a un

**Comment by benking110181** [comment]
demande a alko sur discord si c liens fonctionne

**Comment by Louis-Petit** [comment]
et de façon générale, aucune sources ne fonctionne.. même échec de lecture ou lien introuvable

**Comment by Louis-Petit** [comment]
mon uptobox est encore valide 23 mois

**Comment by Louis-Petit** [comment]
et oui apparemment ses liens fonctionnaient ce matin.... mais les tiens, là de suite ne fonctionnent pas chez moi

**Comment by benking110181** [comment]
creer une nouvelle issue ici ou sur le github vstream il faudrait que sizanic regarde c pas un probleme U2P

**Comment by Louis-Petit** [comment]
dans la section "problèmes U2P"?

**Comment by benking110181** [comment]
creer une nouvelle comme ca il la verra direct

**Comment by Louis-Petit** [comment]
voila, c'est fait 👍

**Comment by noway80** [comment]
Je vais inclure chrome portable dans U2P pour standardiser 
Attendez un peu

**Comment by noway80** [comment]
https://www.transfernow.net/DDiEiR102020

0.9.6
maj auto pastebin est une option
si des problemes de connexion
mettre actif = 0
et copier les paste en manuel

Ajout chrome portable
c 'est sur ce chrome qu il faut etre connecté
1)demarrer "seleniumPortable.exe" (long la 1ere fois)
2)se connecter sur pasteBin et se logger, fermer
3)ensuite procedure normale pour U2P

test ok sur w10 et 7

Merci de vos retours

**Comment by noway80** [comment]
@toadnam 
j'ai pris la dernière mais j'ai réussi à trouver mon problème. Je vais l'expliquer pour les personnes qui tombent sur la meme erreur que moi...
Je suis allé sur https://chromedriver.chromium.org/downloads et j'ai pris la dernière version de ChromeDriver 86.0.4240.22
Je l'ai mis dans le dossier pastebin et je l'ai lancé.
J'ai ce message dans la boite de dialogue ChromeDriver was started successfully.
et ensuite j'ai relancé u2p et la mise à jour s'est faite toute seule avec mon pastebin. :-)
Si cela peut aider d'autres personnes...
Merci en tout cas

En fait la version du chromedriver doit être adaptée à chrome
Tu as du le changer car tu dois avoir la version 86... de chrome 
Une des raisons pour lesquelles, on a mis une version portable

**Comment by toadnam** [comment]
u2p0.9.8.0.1
je n'arrive plus à uploader automatiquement mes séries... je sais pas ou ca coince... :-(
 je lance u2p, il fait son scan et termine sur ca : 
11-10 19:19:08 :: MakePastebin.Main :: INFO :: Serie Houdini => (0)
11-10 19:19:14 :: MakePastebin.renameMedia :: ERROR :: err => 'NoneType' object has no attribute 'group': Houdini.Part.2.
11-10 19:19:14 :: MakePastebin.renameMedia :: ERROR :: err => 'NoneType' object has no attribute 'group': Houdini.Part.1.
11-10 19:19:14 :: MakePastebin.Main :: INFO :: Houdini => vide
11-10 19:19:14 :: MakePastebin.Main :: INFO :: Serie Hostages US => (0)
11-10 19:19:14 :: MakePastebin.UptoToPastebin :: INFO :: pas de resultat recherche Serie TMDB: Hostages US
11-10 19:19:14 :: MakePastebin.Main :: INFO :: Inconnu => Hostages US
11-10 19:19:15 :: MakePastebin.CatSerie :: INFO :: Pastebin Series Crees
11-10 19:19:16 :: MakePastebin.Main :: INFO :: U2P 0.9.8 (utopie) exporte fichier d'un compte (Uptobox/1fichier) => vStream

Quand je consulte mon pastebin sur le site , rien n'a changé...

2ème point : j'ai 3 séries avec une erreur, je sais que je dois faire un fichier texte dans le dossier correctionScan mais j'ai pas compris quelle ligne je devais mettre dans le fichier texte? en sachant que dans le fichier extractSeries_Moncompte_P0 , elle ne figure pas. (houdini 49157 // hostages 55083 // House Of Saddam 7597) 


3ème point : pouquoi ca me crée un fichier extract_Series_Moncompte_P0 alors que sur l'ancienne version c'était extractSeries_Moncompte  ?

Merci d'avance

**Comment by noway80** [comment]
encart pastebin
actif coché?
si oui chrome s'ouvre ?

**Comment by toadnam** [comment]
u2p0.9.6c

ca fonctionne mon upload de séries avec cette version , j'ai pas encore trouvé l'histoire pour corriger mes erreurs mais je cherche ;-)

donc je vais chercher encore

**Comment by toadnam** [comment]
> encart pastebin
> actif coché?
> si oui chrome s'ouvre ?

oui c'est bien coché, et oui chrome s ouvre et se connecte sur pastebin

**Comment by toadnam** [comment]
![U2P](https://user-images.githubusercontent.com/32879272/95686157-82429d80-0bfc-11eb-9843-bb4697cd6aac.png)

**Comment by noway80** [comment]
ok vu j'ai changé beaucoup de choses
je corrige et je poste
merci
extract_Series_Moncompte_P0 pourquoi?
limite pastebin 500ko
au dessus ca cree un extract_Series_Moncompte_P1 etc

**Comment by noway80** [comment]
decoche cast

Houdini.Part.1.
essai Houdini.s01e01

Hostages US
enleve US
et rescan

**Comment by toadnam** [comment]
> ok vu j'ai changé beaucoup de choses
> je corrige et je poste
> merci
> extract_Series_Moncompte_P0 pourquoi?
> limite pastebin 500ko
> au dessus ca cree un extract_Series_Moncompte_P1 etc

Ah ok je croyais que j avais mal config qq chose

**Comment by noway80** [comment]
c est en ligne, test et dis moi

**Comment by toadnam** [comment]
alors j ai plus d erreur en renommant sur uptobox en s01e01...
Mais il n a pas fait l injection je vais rejeter un oeil à mon u2p config

**Comment by toadnam** [comment]
quand je décoche cast ca decoche pastebin... donc j'suis allé le faire manuellement dans le fichier en mettant cast 0 et pastebin 1.
mais ca n'a pas injecté non plus... :-(

**Comment by noway80** [comment]
tas bien ./extractPastebin/extractSeries_moncompte_P0.txt

**Comment by noway80** [comment]
donne la version de u2p?
a la fin du log

**Comment by toadnam** [comment]
> donne la version de u2p?
> a la fin du log

 MakePastebin.Main :: INFO :: U2P 0.9.8 (utopie) exporte fichier d'un compte (Uptobox/1fichier) => vStream





> tas bien ./extractPastebin/extractSeries_moncompte_P0.txt

oui j'ai bien mes 3 séries qui etaient en err avant

**Comment by noway80** [comment]
J ai posté la 0.9.8b qui corrige pastebin

**Comment by toadnam** [comment]
> J ai posté la 0.9.8b qui corrige pastebin
ah mince ya pâs lgtps alors je fais la maj et je te dis ;)

**Comment by toadnam** [comment]
j'ai testé et ca ne marche pas l injection ... :-( 
mais j'ai bien dans mon fichier extract : serie;55083;Hostages;01;[];[];[];['16:CBS'];2013;[18];[];{1: "ifsojgt40j7h", 2: "yebhyay357pi", 6: "56ojfi579qot", 3: "htwa0kfyzynm", 5: "m8ubf3hyq9tk", 4: "rfaxxo7ignze", 7: "3v322sg3jxw0", 8: "jpzwusk2vwmf"} et les autres...
je vois pas où ca bloque...

J'ai remarqué que si je decoche cast, ca dechoche pastebin, si je coche pastebin ca coche cast.
si je coche séries ca coche pastebin et cast.

mais avant d'up je vérifie le fichier config et je remet cast à 0 et pastebin à 1 si besoin ...

**Comment by noway80** [comment]
Ok j ai testé avec film c est ok , vais tester avec series pour voir le pb
Merci

**Comment by toadnam** [comment]
j'attendrai la prochaine version pas grave lol
j'ai mis manuellement mes extracts.

**Comment by alKODIque** [comment]
@toadnam 
J'ai exactement la même situation avec les séries (crochet a cast et pastebin) 😉

@noway80 
je suis ravie de voir qu'enfin, il ny a plus que moi qui déclare des situations bizarres qui se produisent 😂😂😂

**Comment by noway80** [comment]
essayer avec la 0.9.8c

pour configU2P.exe c'est plus grave , les problemes relevés ne sont que sur la version compilée

faut que je cherche

**Comment by noway80** [comment]
merci de retester l'ensemble
j 'ai change de compilateur a priori c etait ca

**Comment by noway80** [comment]
attention correcteur TMDB , ya que ffilm qui fonctionne , la version postée ya les debuts de serie mais pas opreationnelle

**Comment by alKODIque** [comment]
@noway80 
Je teste
Je te tiens aux faits ;)

**Comment by alKODIque** [comment]
@noway80 
Selenium Chrome ne trouve pas chrome portable 
Faut-il installer le exe a un endroit spécial sur le pc afin qu'il soit repéré par selenium?

**Comment by alKODIque** [comment]
Voir mes commentaires ici: https://github.com/Up2Paste/Windows/issues/3#issuecomment-706788989

**Comment by alKODIque** [comment]
Voir mes commentaires ici: https://github.com/Up2Paste/Windows/issues/3#issuecomment-706788989

**Comment by noway80** [comment]
Copie dans le dossier de la nouvelle version les dossiers de l ancienne 
bd
Config
Chromeportable 

Tu lances configU2P.exe
Il devrait tout récupérer  et après comme d hab

Test aussi tmdb correction

**Comment by alKODIque** [comment]
@noway80 
Aussi dans mon cas les etreurs @Anacondas..." sont due aux caractères accentués

**Comment by noway80** [comment]
Oui c zst des erreurs du logger sans gravité

**Comment by noway80** [comment]
Tu as capture erreur ?

**Comment by alKODIque** [comment]
Ouaip!
Juste une capture mais j'ai regardé les autres et toutes étaient semblables: caractères accentués!

![2020-10-12 at 00-34-55 (2)](https://user-images.githubusercontent.com/49578130/95706332-95696380-0c24-11eb-9002-ce509a30a06c.png)

**Comment by noway80** [comment]
Oui c est pas grave,  faut que je formate le texte
Tiens moi au courant pour le reste, la transition est importante de configU2p , beaucoup de fonctionnalités vont arriver dessus

**Comment by alKODIque** [comment]
@noway80 
Aussi j'ai remarqué qu'il ne faut pas utiliser les "cédilles" ni le caractère "&" dans un titre sinon u2p plante

**Comment by alKODIque** [comment]
@noway80  tu iras voir mon commentaire dans l'autre issue "Évolution u2p"

**Comment by noway80** [comment]
Plante ou message d erreur?

**Comment by alKODIque** [comment]
> Plante ou message d erreur?

Plante carrément! impossible de scanner mes séries Qc après avoir ajouté "Karl & Max" ça m'a pris du temps avant de cibler le problème mais dès que j'ai retiré le "&" et remplacé par "et" ça a fonctionné à nouveau...

Par contre pour la cédille il faut que je reproduise pour être certaine à 100%

**Comment by noway80** [comment]
Ok je regarderai 
Merci
Pour inclure censure.txt   c est fonctionnalité qu aura config par la suite

**Comment by alKODIque** [comment]
Ha! 
autre point: il ne faut plus changer le nom de la bd une fois que nous l'avons attribué dans la fenêtre de configuration sinon ça plante également... Il faudrait soit le mentionner, soit griser la case une fois que nous avons nommé (je parle de la case Config ou par défaut est inscrit test)

EDIT:
@noway80 
Je parle du nom de cette fenêtre 

![25335E5F-8D52-4654-970F-34F83AF67E5F](https://user-images.githubusercontent.com/49578130/95707728-59380200-0c28-11eb-84e1-a6c845ecbe2f.png)

**Comment by noway80** [comment]
Ben non j ai fait plusieurs test
Je vérifiais

**Comment by alKODIque** [comment]
ok mais par 3 fois, ça a pas fonctionné pour moi... je referai un test ... il est possible que j'ai fait lorsque j'avais mon problème avec le "&" aussi.. 

Je te confirmerai également donc

**Comment by noway80** [comment]
Tu changes le nom, tu sauve s
Normalement ta aucun soucis

**Comment by alKODIque** [comment]
> Tu changes le nom, tu sauve s
> Normalement ta aucun soucis

Puisque mes autres problèmes sont ciblés et réglés, je referai l'essai sans faute lors de mon prochain scan  et mon résultat sera fiable alors

**Comment by alKODIque** [comment]
@noway80 
Alors j'ai changé le nom dans la case et le scan des films recommence comme si c'était la 1ère fois. 

J'ai stoppé et je vais aller renommer manuellement ma bd au même nom pour voir si ça va fonctionner 

EDIT:
Donc comme tu as mentionné plus haut, il est possible de renommer dans l'interface. 

Par contre, il faut s'assurer que notre bd existante contenant l'historique soit aussi renommée manuellement sinon tout repart à zéro avec un nouveau fichier mediaVstream qui se crée

**Comment by noway80** [comment]
Alko
Tu changes le nom tu sauvegardes, tu quittes
T ouvres le fichier config et tu vois si le nom a été changé

**Comment by alKODIque** [comment]
ok
la je viens de tester correction tmdb et ça fonctionne super bien!

Je fais ce que tu viens de me dire et te reviens

**Comment by alKODIque** [comment]
> Alko
> Tu changes le nom tu sauvegardes, tu quittes
> T ouvres le fichier config et tu vois si le nom a été changé

Ca a pas été changé je viens d'essayer à 2 reprises

**Comment by noway80** [comment]
Ok je vérifies ce soir

**Comment by alKODIque** [comment]
@noway80 

Un dernier petit souci 

Lorsque je retourne faire une modification à l'intérieur de l'interface de configuration, je dois entrer à nouveau chaque fois le nom du répertoire distant, sinon, u2p ne démarre pas.  La raison est que le nom revient entre parenthèse donc n'est plus reconnu.  Voir l'image:

![2020-10-12 at 04-01-30](https://user-images.githubusercontent.com/49578130/95721152-2d287b00-0c40-11eb-9025-13de0c431505.png)
